import os
import numpy as np
from tkinter.simpledialog import askstring

from Foraggio import erba_loietto, erba_medica_disidratata_15x100, erba_medica_disidratata_17x100, erba_medica_II_taglio, erba_prato_stabile, fieno_loietto, fieno_medica_I_taglio, fieno_medica_II_taglio, fieno_prato_stabile_I_taglio, fieno_prato_stabile_II_taglio, fieno_silos_medica, insilato_loietto, insilato_mais, paglia_frumento, pastone_mais_granella, pastone_mais_integrale

from Cereale import avena, frumento_tenero, mais_granella, orzo, sorgo, triticale

from Farina_di_estrazione import arachide_farina_estrazione, colza_farina_estrazione, cotone_farina_estrazione, girasole_farina_estrazione_24x100, girasole_farina_estrazione_34x100, lino_farina_estrazione, soia_farina_estrazione_45x100, soia_farina_estrazione_50x100

from Fonte_di_fibra import bietola_polpe_secche, bietola_polpe_surpressate, carruba_polpa_denocciolata, cotone_semi, crusca_frumento_duro, crusca_frumento_tenero, cruschello_frumento_duro, cruschello_frumento_tenero, frumento_duro_farinaccio, frumento_tenero_farinaccio, frumento_tritello, mais_glutine, mais_residui_distilleria, mais_semola_glutinata, orzo_radichette_malto, orzo_trebbie_birra, riso_farinaccio, soia_buccette

from Leguminosa import favino, lupino, pisello, soia_integrale

from Sottoprodotto import agrumi_pastazzo_secco, birra_lievito, calcio_saponi, cocco_pannello, frumento_tenero_germe, latte_magro_polvere, latte_siero, manioca, melasso_barbabietola, melasso_canna, patate_essiccate, proteina_patata, riso_gemma, riso_grana_verde, riso_pula_commerciale, riso_pula_vergine, riso_rottura     

f = '*\t\t  *\n*\t\t  *\n*\t\t  *\n*     FORAGGI\t  *\n*\t\t  *\n*\t\t  *\n*\t\t  *\n*\t\t  *'
c = '*\t\t  *\n*\t\t  *\n*\t\t  *\n*     CEREALI\t  *\n*\t\t  *\n*\t\t  *\n*\t\t  *\n*\t\t  *'
fe = '*\t\t  *\n*\t\t  *\n*\t\t  *\n*  FARINE DI      *\n*  ESTRAZIONE     *\n*\t\t  *\n*\t\t  *\n*\t\t  *\n*\t\t  *'
ff = '*\t\t  *\n*\t\t  *\n*\t\t  *\n*   FONTI DI      *\n*   FIBRA         *\n*\t\t  *\n*\t\t  *\n*\t\t  *\n*\t\t  *'
le = '*\t\t  *\n*\t\t  *\n*\t\t  *\n*   LEGUMINOSE\t  *\n*\t\t  *\n*\t\t  *\n*\t\t  *\n*\t\t  *'
s = '*\t\t  *\n*\t\t  *\n*\t\t  *\n*  SOTTOPRODOTTI  *\n*\t\t  *\n*\t\t  *\n*\t\t  *\n*\t\t  *'

print('* ' * 10)
print(f)
print('* ' * 10)
print('erba_loietto\nerba_medica_disidratata_15x100\nerba_medica_disidratata_17x100\nerba_medica_II_taglio\nerba_prato_stabile\nfieno_loietto\nfieno_medica_I_taglio\nfieno_medica_II_taglio\nfieno_prato_stabile_I_taglio\nfieno_prato_stabile_II_taglio\nfieno_silos_medica\ninsilato_loietto\ninsilato_mais\npaglia_frumento\npastone_mais_granella\npastone_mais_integrale\n')

print('* ' * 10)
print(c)
print('* ' * 10)
print('avena\nfrumento_tenero\nmais_granella\norzo\nsorgo\ntriticale\n')

print('* ' * 10)
print(fe)
print('* ' * 10)
print('arachide_farina_estrazione\ncolza_farina_estrazione\ncotone_farina_estrazione\ngirasole_farina_estrazione_24x100\ngirasole_farina_estrazione_34x100\nlino_farina_estrazione\nsoia_farina_estrazione_45x100\nsoia_farina_estrazione_50x100\n')

print('* ' * 10)
print(ff)
print('* ' * 10)
print('bietola_polpe_secche\nbietola_polpe_surpressate\ncarruba_polpa_denocciolata\ncotone_semi\ncrusca_frumento_duro\ncrusca_frumento_tenero\ncruschello_frumento_duro\ncruschello_frumento_tenero\nfrumento_duro_farinaccio\nfrumento_tenero_farinaccio\nfrumento_tritello\nmais_glutine\nmais_residui_distilleria\nmais_semola_glutinata\norzo_radichette_malt\noorzo_trebbie_birra\nriso_farinaccio\nsoia_buccette\n')

print('* ' * 10)
print(le)
print('* ' * 10)
print('favino\nlupino\npisello\nsoia_integrale\n')

print('* ' * 10)
print(s)
print('* ' * 10)
print('agrumi_pastazzo_secco\nbirra_lievito\ncalcio_saponi\ncocco_pannello\nfrumento_tenero_germe\nlatte_magro_polvere\nlatte_siero\nmanioca\nmelasso_barbabietola\nmelasso_canna\npatate_essiccate\nproteina_patata\nriso_gemma\nriso_grana_verde\nriso_pula_commerciale\nriso_pula_vergine\nriso_rottura\n')

user = os.getlogin()
os.chdir('/home/%s/COMPUTER_SCIENCE/AI' % user)

foraggi = {}

ERBALOIETTO = list(np.float_(erba_loietto))

ERBALOIETTO_dict = {}
ERBALOIETTO_dict['DM'] = ERBALOIETTO[0]
ERBALOIETTO_dict['PG'] = ERBALOIETTO[1]
ERBALOIETTO_dict['RDP'] = ERBALOIETTO[2]
ERBALOIETTO_dict['RUP'] = ERBALOIETTO[3]
ERBALOIETTO_dict['FG'] = ERBALOIETTO[4]
ERBALOIETTO_dict['NDF'] = ERBALOIETTO[5]
ERBALOIETTO_dict['ADF'] = ERBALOIETTO[6]
ERBALOIETTO_dict['FAT'] = ERBALOIETTO[7]
ERBALOIETTO_dict['ASH'] = ERBALOIETTO[10]
ERBALOIETTO_dict['Ca'] = ERBALOIETTO[11]
ERBALOIETTO_dict['P'] = ERBALOIETTO[12]
ERBALOIETTO_dict['Mg'] = ERBALOIETTO[13]
ERBALOIETTO_dict['K'] = ERBALOIETTO[14]
ERBALOIETTO_dict['S'] = ERBALOIETTO[15]
ERBALOIETTO_dict['Na'] = ERBALOIETTO[16]
ERBALOIETTO_dict['UFC'] = ERBALOIETTO[17]
ERBALOIETTO_dict['UFL'] = ERBALOIETTO[18]
ERBALOIETTO_dict['kcal'] = ERBALOIETTO[19]
ERBALOIETTO_dict['Mj'] = ERBALOIETTO[20]
#print(ERBALOIETTO_dict)

ERBAMEDICADIS15 = list(np.float_(erba_medica_disidratata_15x100))

ERBAMEDICADIS15_dict = {}
ERBAMEDICADIS15_dict['DM'] = ERBAMEDICADIS15[0]
ERBAMEDICADIS15_dict['PG'] = ERBAMEDICADIS15[1]
ERBAMEDICADIS15_dict['RDP'] = ERBAMEDICADIS15[2]
ERBAMEDICADIS15_dict['RUP'] = ERBAMEDICADIS15[3]
ERBAMEDICADIS15_dict['FG'] = ERBAMEDICADIS15[4]
ERBAMEDICADIS15_dict['NDF'] = ERBAMEDICADIS15[5]
ERBAMEDICADIS15_dict['ADF'] = ERBAMEDICADIS15[6]
ERBAMEDICADIS15_dict['FAT'] = ERBAMEDICADIS15[7]
ERBAMEDICADIS15_dict['ASH'] = ERBAMEDICADIS15[10]
ERBAMEDICADIS15_dict['Ca'] = ERBAMEDICADIS15[11]
ERBAMEDICADIS15_dict['P'] = ERBAMEDICADIS15[12]
ERBAMEDICADIS15_dict['Mg'] = ERBAMEDICADIS15[13]
ERBAMEDICADIS15_dict['K'] = ERBAMEDICADIS15[14]
ERBAMEDICADIS15_dict['S'] = ERBAMEDICADIS15[15]
ERBAMEDICADIS15_dict['Na'] = ERBAMEDICADIS15[16]
ERBAMEDICADIS15_dict['UFC'] = ERBAMEDICADIS15[17]
ERBAMEDICADIS15_dict['UFL'] = ERBAMEDICADIS15[18]
ERBAMEDICADIS15_dict['kcal'] = ERBAMEDICADIS15[19]
ERBAMEDICADIS15_dict['Mj'] = ERBAMEDICADIS15[20]
#print(ERBAMEDICADIS15_dict)

ERBAMEDICADIS17 = list(np.float_(erba_medica_disidratata_17x100))

ERBAMEDICADIS17_dict = {}
ERBAMEDICADIS17_dict['DM'] = ERBAMEDICADIS17[0]
ERBAMEDICADIS17_dict['PG'] = ERBAMEDICADIS17[1]
ERBAMEDICADIS17_dict['RDP'] = ERBAMEDICADIS17[2]
ERBAMEDICADIS17_dict['RUP'] = ERBAMEDICADIS17[3]
ERBAMEDICADIS17_dict['FG'] = ERBAMEDICADIS17[4]
ERBAMEDICADIS17_dict['NDF'] = ERBAMEDICADIS17[5]
ERBAMEDICADIS17_dict['ADF'] = ERBAMEDICADIS17[6]
ERBAMEDICADIS17_dict['FAT'] = ERBAMEDICADIS17[7]
ERBAMEDICADIS17_dict['ASH'] = ERBAMEDICADIS17[10]
ERBAMEDICADIS17_dict['Ca'] = ERBAMEDICADIS17[11]
ERBAMEDICADIS17_dict['P'] = ERBAMEDICADIS17[12]
ERBAMEDICADIS17_dict['Mg'] = ERBAMEDICADIS17[13]
ERBAMEDICADIS17_dict['K'] = ERBAMEDICADIS17[14]
ERBAMEDICADIS17_dict['S'] = ERBAMEDICADIS17[15]
ERBAMEDICADIS17_dict['Na'] = ERBAMEDICADIS17[16]
ERBAMEDICADIS17_dict['UFC'] = ERBAMEDICADIS17[17]
ERBAMEDICADIS17_dict['UFL'] = ERBAMEDICADIS17[18]
ERBAMEDICADIS17_dict['kcal'] = ERBAMEDICADIS17[19]
ERBAMEDICADIS17_dict['Mj'] = ERBAMEDICADIS17[20]
#print(ERBAMEDICADIS17_dict)

ERBAMEDICA2 = list(np.float_(erba_medica_II_taglio))

ERBAMEDICA2_dict = {}
ERBAMEDICA2_dict['DM'] = ERBAMEDICA2[0]
ERBAMEDICA2_dict['PG'] = ERBAMEDICA2[1]
ERBAMEDICA2_dict['RDP'] = ERBAMEDICA2[2]
ERBAMEDICA2_dict['RUP'] = ERBAMEDICA2[3]
ERBAMEDICA2_dict['FG'] = ERBAMEDICA2[4]
ERBAMEDICA2_dict['NDF'] = ERBAMEDICA2[5]
ERBAMEDICA2_dict['ADF'] = ERBAMEDICA2[6]
ERBAMEDICA2_dict['FAT'] = ERBAMEDICA2[7]
ERBAMEDICA2_dict['ASH'] = ERBAMEDICA2[10]
ERBAMEDICA2_dict['Ca'] = ERBAMEDICA2[11]
ERBAMEDICA2_dict['P'] = ERBAMEDICA2[12]
ERBAMEDICA2_dict['Mg'] = ERBAMEDICA2[13]
ERBAMEDICA2_dict['K'] = ERBAMEDICA2[14]
ERBAMEDICA2_dict['S'] = ERBAMEDICA2[15]
ERBAMEDICA2_dict['Na'] = ERBAMEDICA2[16]
ERBAMEDICA2_dict['UFC'] = ERBAMEDICA2[17]
ERBAMEDICA2_dict['UFL'] = ERBAMEDICA2[18]
ERBAMEDICA2_dict['kcal'] = ERBAMEDICA2[19]
ERBAMEDICA2_dict['Mj'] = ERBAMEDICA2[20]
#print(ERBAMEDICA2_dict)

ERBAPRASTA = list(np.float_(erba_prato_stabile))

ERBAPRASTA_dict = {}
ERBAPRASTA_dict['DM'] = ERBAPRASTA[0]
ERBAPRASTA_dict['PG'] = ERBAPRASTA[1]
ERBAPRASTA_dict['RDP'] = ERBAPRASTA[2]
ERBAPRASTA_dict['RUP'] = ERBAPRASTA[3]
ERBAPRASTA_dict['FG'] = ERBAPRASTA[4]
ERBAPRASTA_dict['NDF'] = ERBAPRASTA[5]
ERBAPRASTA_dict['ADF'] = ERBAPRASTA[6]
ERBAPRASTA_dict['FAT'] = ERBAPRASTA[7]
ERBAPRASTA_dict['ASH'] = ERBAPRASTA[10]
ERBAPRASTA_dict['Ca'] = ERBAPRASTA[11]
ERBAPRASTA_dict['P'] = ERBAPRASTA[12]
ERBAPRASTA_dict['Mg'] = ERBAPRASTA[13]
ERBAPRASTA_dict['K'] = ERBAPRASTA[14]
ERBAPRASTA_dict['S'] = ERBAPRASTA[15]
ERBAPRASTA_dict['Na'] = ERBAPRASTA[16]
ERBAPRASTA_dict['UFC'] = ERBAPRASTA[17]
ERBAPRASTA_dict['UFL'] = ERBAPRASTA[18]
ERBAPRASTA_dict['kcal'] = ERBAPRASTA[19]
ERBAPRASTA_dict['Mj'] = ERBAPRASTA[20]
#print(ERBAPRASTA_dict)

FIENOLOIETTO = list(np.float_(fieno_loietto))

FIENOLOIETTO_dict = {}
FIENOLOIETTO_dict['DM'] = FIENOLOIETTO[0]
FIENOLOIETTO_dict['PG'] = FIENOLOIETTO[1]
FIENOLOIETTO_dict['RDP'] = FIENOLOIETTO[2]
FIENOLOIETTO_dict['RUP'] = FIENOLOIETTO[3]
FIENOLOIETTO_dict['FG'] = FIENOLOIETTO[4]
FIENOLOIETTO_dict['NDF'] = FIENOLOIETTO[5]
FIENOLOIETTO_dict['ADF'] = FIENOLOIETTO[6]
FIENOLOIETTO_dict['FAT'] = FIENOLOIETTO[7]
FIENOLOIETTO_dict['ASH'] = FIENOLOIETTO[10]
FIENOLOIETTO_dict['Ca'] = FIENOLOIETTO[11]
FIENOLOIETTO_dict['P'] = FIENOLOIETTO[12]
FIENOLOIETTO_dict['Mg'] = FIENOLOIETTO[13]
FIENOLOIETTO_dict['K'] = FIENOLOIETTO[14]
FIENOLOIETTO_dict['S'] = FIENOLOIETTO[15]
FIENOLOIETTO_dict['Na'] = FIENOLOIETTO[16]
FIENOLOIETTO_dict['UFC'] = FIENOLOIETTO[17]
FIENOLOIETTO_dict['UFL'] = FIENOLOIETTO[18]
FIENOLOIETTO_dict['kcal'] = FIENOLOIETTO[19]
FIENOLOIETTO_dict['Mj'] = FIENOLOIETTO[20]
#print(FIENOLOIETTO_dict)

FIEALIMENTOD1 = list(np.float_(fieno_medica_I_taglio))

FIEALIMENTOD1_dict = {}
FIEALIMENTOD1_dict['DM'] = FIEALIMENTOD1[0]
FIEALIMENTOD1_dict['PG'] = FIEALIMENTOD1[1]
FIEALIMENTOD1_dict['RDP'] = FIEALIMENTOD1[2]
FIEALIMENTOD1_dict['RUP'] = FIEALIMENTOD1[3]
FIEALIMENTOD1_dict['FG'] = FIEALIMENTOD1[4]
FIEALIMENTOD1_dict['NDF'] = FIEALIMENTOD1[5]
FIEALIMENTOD1_dict['ADF'] = FIEALIMENTOD1[6]
FIEALIMENTOD1_dict['FAT'] = FIEALIMENTOD1[7]
FIEALIMENTOD1_dict['ASH'] = FIEALIMENTOD1[10]
FIEALIMENTOD1_dict['Ca'] = FIEALIMENTOD1[11]
FIEALIMENTOD1_dict['P'] = FIEALIMENTOD1[12]
FIEALIMENTOD1_dict['Mg'] = FIEALIMENTOD1[13]
FIEALIMENTOD1_dict['K'] = FIEALIMENTOD1[14]
FIEALIMENTOD1_dict['S'] = FIEALIMENTOD1[15]
FIEALIMENTOD1_dict['Na'] = FIEALIMENTOD1[16]
FIEALIMENTOD1_dict['UFC'] = FIEALIMENTOD1[17]
FIEALIMENTOD1_dict['UFL'] = FIEALIMENTOD1[18]
FIEALIMENTOD1_dict['kcal'] = FIEALIMENTOD1[19]
FIEALIMENTOD1_dict['Mj'] = FIEALIMENTOD1[20]
#print(FIEALIMENTOD1_dict)

FIEALIMENTOD2 = list(np.float_(fieno_medica_II_taglio))

FIEALIMENTOD2_dict = {}
FIEALIMENTOD2_dict['DM'] = FIEALIMENTOD2[0]
FIEALIMENTOD2_dict['PG'] = FIEALIMENTOD2[1]
FIEALIMENTOD2_dict['RDP'] = FIEALIMENTOD2[2]
FIEALIMENTOD2_dict['RUP'] = FIEALIMENTOD2[3]
FIEALIMENTOD2_dict['FG'] = FIEALIMENTOD2[4]
FIEALIMENTOD2_dict['NDF'] = FIEALIMENTOD2[5]
FIEALIMENTOD2_dict['ADF'] = FIEALIMENTOD2[6]
FIEALIMENTOD2_dict['FAT'] = FIEALIMENTOD2[7]
FIEALIMENTOD2_dict['ASH'] = FIEALIMENTOD2[10]
FIEALIMENTOD2_dict['Ca'] = FIEALIMENTOD2[11]
FIEALIMENTOD2_dict['P'] = FIEALIMENTOD2[12]
FIEALIMENTOD2_dict['Mg'] = FIEALIMENTOD2[13]
FIEALIMENTOD2_dict['K'] = FIEALIMENTOD2[14]
FIEALIMENTOD2_dict['S'] = FIEALIMENTOD2[15]
FIEALIMENTOD2_dict['Na'] = FIEALIMENTOD2[16]
FIEALIMENTOD2_dict['UFC'] = FIEALIMENTOD2[17]
FIEALIMENTOD2_dict['UFL'] = FIEALIMENTOD2[18]
FIEALIMENTOD2_dict['kcal'] = FIEALIMENTOD2[19]
FIEALIMENTOD2_dict['Mj'] = FIEALIMENTOD2[20]
#print(FIEALIMENTOD2_dict)

FIEPRASTA1TA = list(np.float_(fieno_prato_stabile_I_taglio))

FIEPRASTA1TA_dict = {}
FIEPRASTA1TA_dict['DM'] = FIEPRASTA1TA[0]
FIEPRASTA1TA_dict['PG'] = FIEPRASTA1TA[1]
FIEPRASTA1TA_dict['RDP'] = FIEPRASTA1TA[2]
FIEPRASTA1TA_dict['RUP'] = FIEPRASTA1TA[3]
FIEPRASTA1TA_dict['FG'] = FIEPRASTA1TA[4]
FIEPRASTA1TA_dict['NDF'] = FIEPRASTA1TA[5]
FIEPRASTA1TA_dict['ADF'] = FIEPRASTA1TA[6]
FIEPRASTA1TA_dict['FAT'] = FIEPRASTA1TA[7]
FIEPRASTA1TA_dict['ASH'] = FIEPRASTA1TA[10]
FIEPRASTA1TA_dict['Ca'] = FIEPRASTA1TA[11]
FIEPRASTA1TA_dict['P'] = FIEPRASTA1TA[12]
FIEPRASTA1TA_dict['Mg'] = FIEPRASTA1TA[13]
FIEPRASTA1TA_dict['K'] = FIEPRASTA1TA[14]
FIEPRASTA1TA_dict['S'] = FIEPRASTA1TA[15]
FIEPRASTA1TA_dict['Na'] = FIEPRASTA1TA[16]
FIEPRASTA1TA_dict['UFC'] = FIEPRASTA1TA[17]
FIEPRASTA1TA_dict['UFL'] = FIEPRASTA1TA[18]
FIEPRASTA1TA_dict['kcal'] = FIEPRASTA1TA[19]
FIEPRASTA1TA_dict['Mj'] = FIEPRASTA1TA[20]
#print(FIEPRASTA1TA_dict)

FIEPRASTA2TA = list(np.float_(fieno_prato_stabile_II_taglio))

FIEPRASTA2TA_dict = {}
FIEPRASTA2TA_dict['DM'] = FIEPRASTA2TA[0]
FIEPRASTA2TA_dict['PG'] = FIEPRASTA2TA[1]
FIEPRASTA2TA_dict['RDP'] = FIEPRASTA2TA[2]
FIEPRASTA2TA_dict['RUP'] = FIEPRASTA2TA[3]
FIEPRASTA2TA_dict['FG'] = FIEPRASTA2TA[4]
FIEPRASTA2TA_dict['NDF'] = FIEPRASTA2TA[5]
FIEPRASTA2TA_dict['ADF'] = FIEPRASTA2TA[6]
FIEPRASTA2TA_dict['FAT'] = FIEPRASTA2TA[7]
FIEPRASTA2TA_dict['ASH'] = FIEPRASTA2TA[10]
FIEPRASTA2TA_dict['Ca'] = FIEPRASTA2TA[11]
FIEPRASTA2TA_dict['P'] = FIEPRASTA2TA[12]
FIEPRASTA2TA_dict['Mg'] = FIEPRASTA2TA[13]
FIEPRASTA2TA_dict['K'] = FIEPRASTA2TA[14]
FIEPRASTA2TA_dict['S'] = FIEPRASTA2TA[15]
FIEPRASTA2TA_dict['Na'] = FIEPRASTA2TA[16]
FIEPRASTA2TA_dict['UFC'] = FIEPRASTA2TA[17]
FIEPRASTA2TA_dict['UFL'] = FIEPRASTA2TA[18]
FIEPRASTA2TA_dict['kcal'] = FIEPRASTA2TA[19]
FIEPRASTA2TA_dict['Mj'] = FIEPRASTA2TA[20]
#print(FIEPRASTA2TA_dict)

FIENOSILOMED = list(np.float_(fieno_silos_medica))

FIENOSILOMED_dict = {}
FIENOSILOMED_dict['DM'] = FIENOSILOMED[0]
FIENOSILOMED_dict['PG'] = FIENOSILOMED[1]
FIENOSILOMED_dict['RDP'] = FIENOSILOMED[2]
FIENOSILOMED_dict['RUP'] = FIENOSILOMED[3]
FIENOSILOMED_dict['FG'] = FIENOSILOMED[4]
FIENOSILOMED_dict['NDF'] = FIENOSILOMED[5]
FIENOSILOMED_dict['ADF'] = FIENOSILOMED[6]
FIENOSILOMED_dict['FAT'] = FIENOSILOMED[7]
FIENOSILOMED_dict['ASH'] = FIENOSILOMED[10]
FIENOSILOMED_dict['Ca'] = FIENOSILOMED[11]
FIENOSILOMED_dict['P'] = FIENOSILOMED[12]
FIENOSILOMED_dict['Mg'] = FIENOSILOMED[13]
FIENOSILOMED_dict['K'] = FIENOSILOMED[14]
FIENOSILOMED_dict['S'] = FIENOSILOMED[15]
FIENOSILOMED_dict['Na'] = FIENOSILOMED[16]
FIENOSILOMED_dict['UFC'] = FIENOSILOMED[17]
FIENOSILOMED_dict['UFL'] = FIENOSILOMED[18]
FIENOSILOMED_dict['kcal'] = FIENOSILOMED[19]
FIENOSILOMED_dict['Mj'] = FIENOSILOMED[20]
#print(FIENOSILOMED_dict)

INSILOIETTO = list(np.float_(insilato_loietto))

INSILOIETTO_dict = {}
INSILOIETTO_dict['DM'] = INSILOIETTO[0]
INSILOIETTO_dict['PG'] = INSILOIETTO[1]
INSILOIETTO_dict['RDP'] = INSILOIETTO[2]
INSILOIETTO_dict['RUP'] = INSILOIETTO[3]
INSILOIETTO_dict['FG'] = INSILOIETTO[4]
INSILOIETTO_dict['NDF'] = INSILOIETTO[5]
INSILOIETTO_dict['ADF'] = INSILOIETTO[6]
INSILOIETTO_dict['FAT'] = INSILOIETTO[7]
INSILOIETTO_dict['ASH'] = INSILOIETTO[10]
INSILOIETTO_dict['Ca'] = INSILOIETTO[11]
INSILOIETTO_dict['P'] = INSILOIETTO[12]
INSILOIETTO_dict['Mg'] = INSILOIETTO[13]
INSILOIETTO_dict['K'] = INSILOIETTO[14]
INSILOIETTO_dict['S'] = INSILOIETTO[15]
INSILOIETTO_dict['Na'] = INSILOIETTO[16]
INSILOIETTO_dict['UFC'] = INSILOIETTO[17]
INSILOIETTO_dict['UFL'] = INSILOIETTO[18]
INSILOIETTO_dict['kcal'] = INSILOIETTO[19]
INSILOIETTO_dict['Mj'] = INSILOIETTO[20]
#print(INSILOIETTO_dict)

INSILOMAIS = list(np.float_(insilato_mais))

INSILOMAIS_dict = {}
INSILOMAIS_dict['DM'] = INSILOMAIS[0]
INSILOMAIS_dict['PG'] = INSILOMAIS[1]
INSILOMAIS_dict['RDP'] = INSILOMAIS[2]
INSILOMAIS_dict['RUP'] = INSILOMAIS[3]
INSILOMAIS_dict['FG'] = INSILOMAIS[4]
INSILOMAIS_dict['NDF'] = INSILOMAIS[5]
INSILOMAIS_dict['ADF'] = INSILOMAIS[6]
INSILOMAIS_dict['FAT'] = INSILOMAIS[7]
INSILOMAIS_dict['ASH'] = INSILOMAIS[10]
INSILOMAIS_dict['Ca'] = INSILOMAIS[11]
INSILOMAIS_dict['P'] = INSILOMAIS[12]
INSILOMAIS_dict['Mg'] = INSILOMAIS[13]
INSILOMAIS_dict['K'] = INSILOMAIS[14]
INSILOMAIS_dict['S'] = INSILOMAIS[15]
INSILOMAIS_dict['Na'] = INSILOMAIS[16]
INSILOMAIS_dict['UFC'] = INSILOMAIS[17]
INSILOMAIS_dict['UFL'] = INSILOMAIS[18]
INSILOMAIS_dict['kcal'] = INSILOMAIS[19]
INSILOMAIS_dict['Mj'] = INSILOMAIS[20]
#print(INSILOMAIS_dict)

PAGLIA = list(np.float_(paglia_frumento))

PAGLIA_dict = {}
PAGLIA_dict['DM'] = PAGLIA[0]
PAGLIA_dict['PG'] = PAGLIA[1]
PAGLIA_dict['RDP'] = PAGLIA[2]
PAGLIA_dict['RUP'] = PAGLIA[3]
PAGLIA_dict['FG'] = PAGLIA[4]
PAGLIA_dict['NDF'] = PAGLIA[5]
PAGLIA_dict['ADF'] = PAGLIA[6]
PAGLIA_dict['FAT'] = PAGLIA[7]
PAGLIA_dict['ASH'] = PAGLIA[10]
PAGLIA_dict['Ca'] = PAGLIA[11]
PAGLIA_dict['P'] = PAGLIA[12]
PAGLIA_dict['Mg'] = PAGLIA[13]
PAGLIA_dict['K'] = PAGLIA[14]
PAGLIA_dict['S'] = PAGLIA[15]
PAGLIA_dict['Na'] = PAGLIA[16]
PAGLIA_dict['UFC'] = PAGLIA[17]
PAGLIA_dict['UFL'] = PAGLIA[18]
PAGLIA_dict['kcal'] = PAGLIA[19]
PAGLIA_dict['Mj'] = PAGLIA[20]
#print(PAGLIA_dict)

PASTOMAISGRA = list(np.float_(pastone_mais_granella))

PASTOMAISGRA_dict = {}
PASTOMAISGRA_dict['DM'] = PASTOMAISGRA[0]
PASTOMAISGRA_dict['PG'] = PASTOMAISGRA[1]
PASTOMAISGRA_dict['RDP'] = PASTOMAISGRA[2]
PASTOMAISGRA_dict['RUP'] = PASTOMAISGRA[3]
PASTOMAISGRA_dict['FG'] = PASTOMAISGRA[4]
PASTOMAISGRA_dict['NDF'] = PASTOMAISGRA[5]
PASTOMAISGRA_dict['ADF'] = PASTOMAISGRA[6]
PASTOMAISGRA_dict['FAT'] = PASTOMAISGRA[7]
PASTOMAISGRA_dict['ASH'] = PASTOMAISGRA[10]
PASTOMAISGRA_dict['Ca'] = PASTOMAISGRA[11]
PASTOMAISGRA_dict['P'] = PASTOMAISGRA[12]
PASTOMAISGRA_dict['Mg'] = PASTOMAISGRA[13]
PASTOMAISGRA_dict['K'] = PASTOMAISGRA[14]
PASTOMAISGRA_dict['S'] = PASTOMAISGRA[15]
PASTOMAISGRA_dict['Na'] = PASTOMAISGRA[16]
PASTOMAISGRA_dict['UFC'] = PASTOMAISGRA[17]
PASTOMAISGRA_dict['UFL'] = PASTOMAISGRA[18]
PASTOMAISGRA_dict['kcal'] = PASTOMAISGRA[19]
PASTOMAISGRA_dict['Mj'] = PASTOMAISGRA[20]
#print(PASTOMAISGRA_dict)

PASTOMAISINT = list(np.float_(pastone_mais_integrale))

PASTOMAISINT_dict = {}
PASTOMAISINT_dict['DM'] = PASTOMAISINT[0]
PASTOMAISINT_dict['PG'] = PASTOMAISINT[1]
PASTOMAISINT_dict['RDP'] = PASTOMAISINT[2]
PASTOMAISINT_dict['RUP'] = PASTOMAISINT[3]
PASTOMAISINT_dict['FG'] = PASTOMAISINT[4]
PASTOMAISINT_dict['NDF'] = PASTOMAISINT[5]
PASTOMAISINT_dict['ADF'] = PASTOMAISINT[6]
PASTOMAISINT_dict['FAT'] = PASTOMAISINT[7]
PASTOMAISINT_dict['ASH'] = PASTOMAISINT[10]
PASTOMAISINT_dict['Ca'] = PASTOMAISINT[11]
PASTOMAISINT_dict['P'] = PASTOMAISINT[12]
PASTOMAISINT_dict['Mg'] = PASTOMAISINT[13]
PASTOMAISINT_dict['K'] = PASTOMAISINT[14]
PASTOMAISINT_dict['S'] = PASTOMAISINT[15]
PASTOMAISINT_dict['Na'] = PASTOMAISINT[16]
PASTOMAISINT_dict['UFC'] = PASTOMAISINT[17]
PASTOMAISINT_dict['UFL'] = PASTOMAISINT[18]
PASTOMAISINT_dict['kcal'] = PASTOMAISINT[19]
PASTOMAISINT_dict['Mj'] = PASTOMAISINT[20]
#print(PASTOMAISINT_dict)

AVENA = list(np.float_(avena))

AVENA_dict = {}
AVENA_dict['DM'] = AVENA[0]
AVENA_dict['PG'] = AVENA[1]
AVENA_dict['RDP'] = AVENA[2]
AVENA_dict['RUP'] = AVENA[3]
AVENA_dict['FG'] = AVENA[4]
AVENA_dict['NDF'] = AVENA[5]
AVENA_dict['ADF'] = AVENA[6]
AVENA_dict['FAT'] = AVENA[7]
AVENA_dict['ASH'] = AVENA[10]
AVENA_dict['Ca'] = AVENA[11]
AVENA_dict['P'] = AVENA[12]
AVENA_dict['Mg'] = AVENA[13]
AVENA_dict['K'] = AVENA[14]
AVENA_dict['S'] = AVENA[15]
AVENA_dict['Na'] = AVENA[16]
AVENA_dict['UFC'] = AVENA[17]
AVENA_dict['UFL'] = AVENA[18]
AVENA_dict['kcal'] = AVENA[19]
AVENA_dict['Mj'] = AVENA[20]
#print(AVENA_dict)

FRUTENERO = list(np.float_(frumento_tenero))

FRUTENERO_dict = {}
FRUTENERO_dict['DM'] = FRUTENERO[0]
FRUTENERO_dict['PG'] = FRUTENERO[1]
FRUTENERO_dict['RDP'] = FRUTENERO[2]
FRUTENERO_dict['RUP'] = FRUTENERO[3]
FRUTENERO_dict['FG'] = FRUTENERO[4]
FRUTENERO_dict['NDF'] = FRUTENERO[5]
FRUTENERO_dict['ADF'] = FRUTENERO[6]
FRUTENERO_dict['FAT'] = FRUTENERO[7]
FRUTENERO_dict['ASH'] = FRUTENERO[10]
FRUTENERO_dict['Ca'] = FRUTENERO[11]
FRUTENERO_dict['P'] = FRUTENERO[12]
FRUTENERO_dict['Mg'] = FRUTENERO[13]
FRUTENERO_dict['K'] = FRUTENERO[14]
FRUTENERO_dict['S'] = FRUTENERO[15]
FRUTENERO_dict['Na'] = FRUTENERO[16]
FRUTENERO_dict['UFC'] = FRUTENERO[17]
FRUTENERO_dict['UFL'] = FRUTENERO[18]
FRUTENERO_dict['kcal'] = FRUTENERO[19]
FRUTENERO_dict['Mj'] = FRUTENERO[20]
#print(FRUTENERO_dict)

MAISGRA = list(np.float_(mais_granella))

MAISGRA_dict = {}
MAISGRA_dict['DM'] = MAISGRA[0]
MAISGRA_dict['PG'] = MAISGRA[1]
MAISGRA_dict['RDP'] = MAISGRA[2]
MAISGRA_dict['RUP'] = MAISGRA[3]
MAISGRA_dict['FG'] = MAISGRA[4]
MAISGRA_dict['NDF'] = MAISGRA[5]
MAISGRA_dict['ADF'] = MAISGRA[6]
MAISGRA_dict['FAT'] = MAISGRA[7]
MAISGRA_dict['ASH'] = MAISGRA[10]
MAISGRA_dict['Ca'] = MAISGRA[11]
MAISGRA_dict['P'] = MAISGRA[12]
MAISGRA_dict['Mg'] = MAISGRA[13]
MAISGRA_dict['K'] = MAISGRA[14]
MAISGRA_dict['S'] = MAISGRA[15]
MAISGRA_dict['Na'] = MAISGRA[16]
MAISGRA_dict['UFC'] = MAISGRA[17]
MAISGRA_dict['UFL'] = MAISGRA[18]
MAISGRA_dict['kcal'] = MAISGRA[19]
MAISGRA_dict['Mj'] = MAISGRA[20]
#print(MAISGRA_dict)

ORZO = list(np.float_(orzo))

ORZO_dict = {}
ORZO_dict['DM'] = ORZO[0]
ORZO_dict['PG'] = ORZO[1]
ORZO_dict['RDP'] = ORZO[2]
ORZO_dict['RUP'] = ORZO[3]
ORZO_dict['FG'] = ORZO[4]
ORZO_dict['NDF'] = ORZO[5]
ORZO_dict['ADF'] = ORZO[6]
ORZO_dict['FAT'] = ORZO[7]
ORZO_dict['ASH'] = ORZO[10]
ORZO_dict['Ca'] = ORZO[11]
ORZO_dict['P'] = ORZO[12]
ORZO_dict['Mg'] = ORZO[13]
ORZO_dict['K'] = ORZO[14]
ORZO_dict['S'] = ORZO[15]
ORZO_dict['Na'] = ORZO[16]
ORZO_dict['UFC'] = ORZO[17]
ORZO_dict['UFL'] = ORZO[18]
ORZO_dict['kcal'] = ORZO[19]
ORZO_dict['Mj'] = ORZO[20]
#print(ORZO_dict)

SORGO = list(np.float_(sorgo))

SORGO_dict = {}
SORGO_dict['DM'] = SORGO[0]
SORGO_dict['PG'] = SORGO[1]
SORGO_dict['RDP'] = SORGO[2]
SORGO_dict['RUP'] = SORGO[3]
SORGO_dict['FG'] = SORGO[4]
SORGO_dict['NDF'] = SORGO[5]
SORGO_dict['ADF'] = SORGO[6]
SORGO_dict['FAT'] = SORGO[7]
SORGO_dict['ASH'] = SORGO[10]
SORGO_dict['Ca'] = SORGO[11]
SORGO_dict['P'] = SORGO[12]
SORGO_dict['Mg'] = SORGO[13]
SORGO_dict['K'] = SORGO[14]
SORGO_dict['S'] = SORGO[15]
SORGO_dict['Na'] = SORGO[16]
SORGO_dict['UFC'] = SORGO[17]
SORGO_dict['UFL'] = SORGO[18]
SORGO_dict['kcal'] = SORGO[19]
SORGO_dict['Mj'] = SORGO[20]
#print(SORGO_dict)

TRITICALE = list(np.float_(triticale))

TRITICALE_dict = {}
TRITICALE_dict['DM'] = TRITICALE[0]
TRITICALE_dict['PG'] = TRITICALE[1]
TRITICALE_dict['RDP'] = TRITICALE[2]
TRITICALE_dict['RUP'] = TRITICALE[3]
TRITICALE_dict['FG'] = TRITICALE[4]
TRITICALE_dict['NDF'] = TRITICALE[5]
TRITICALE_dict['ADF'] = TRITICALE[6]
TRITICALE_dict['FAT'] = TRITICALE[7]
TRITICALE_dict['ASH'] = TRITICALE[10]
TRITICALE_dict['Ca'] = TRITICALE[11]
TRITICALE_dict['P'] = TRITICALE[12]
TRITICALE_dict['Mg'] = TRITICALE[13]
TRITICALE_dict['K'] = TRITICALE[14]
TRITICALE_dict['S'] = TRITICALE[15]
TRITICALE_dict['Na'] = TRITICALE[16]
TRITICALE_dict['UFC'] = TRITICALE[17]
TRITICALE_dict['UFL'] = TRITICALE[18]
TRITICALE_dict['kcal'] = TRITICALE[19]
TRITICALE_dict['Mj'] = TRITICALE[20]
#print(TRITICALE_dict)

ARACHIDEFE = list(np.float_(arachide_farina_estrazione))

ARACHIDEFE_dict = {}
ARACHIDEFE_dict['DM'] = ARACHIDEFE[0]
ARACHIDEFE_dict['PG'] = ARACHIDEFE[1]
ARACHIDEFE_dict['RDP'] = ARACHIDEFE[2]
ARACHIDEFE_dict['RUP'] = ARACHIDEFE[3]
ARACHIDEFE_dict['FG'] = ARACHIDEFE[4]
ARACHIDEFE_dict['NDF'] = ARACHIDEFE[5]
ARACHIDEFE_dict['ADF'] = ARACHIDEFE[6]
ARACHIDEFE_dict['FAT'] = ARACHIDEFE[7]
ARACHIDEFE_dict['ASH'] = ARACHIDEFE[10]
ARACHIDEFE_dict['Ca'] = ARACHIDEFE[11]
ARACHIDEFE_dict['P'] = ARACHIDEFE[12]
ARACHIDEFE_dict['Mg'] = ARACHIDEFE[13]
ARACHIDEFE_dict['K'] = ARACHIDEFE[14]
ARACHIDEFE_dict['S'] = ARACHIDEFE[15]
ARACHIDEFE_dict['Na'] = ARACHIDEFE[16]
ARACHIDEFE_dict['UFC'] = ARACHIDEFE[17]
ARACHIDEFE_dict['UFL'] = ARACHIDEFE[18]
ARACHIDEFE_dict['kcal'] = ARACHIDEFE[19]
ARACHIDEFE_dict['Mj'] = ARACHIDEFE[20]
#print(ARACHIDEFE_dict)

COLZAFE = list(np.float_(colza_farina_estrazione))

COLZAFE_dict = {}
COLZAFE_dict['DM'] = COLZAFE[0]
COLZAFE_dict['PG'] = COLZAFE[1]
COLZAFE_dict['RDP'] = COLZAFE[2]
COLZAFE_dict['RUP'] = COLZAFE[3]
COLZAFE_dict['FG'] = COLZAFE[4]
COLZAFE_dict['NDF'] = COLZAFE[5]
COLZAFE_dict['ADF'] = COLZAFE[6]
COLZAFE_dict['FAT'] = COLZAFE[7]
COLZAFE_dict['ASH'] = COLZAFE[10]
COLZAFE_dict['Ca'] = COLZAFE[11]
COLZAFE_dict['P'] = COLZAFE[12]
COLZAFE_dict['Mg'] = COLZAFE[13]
COLZAFE_dict['K'] = COLZAFE[14]
COLZAFE_dict['S'] = COLZAFE[15]
COLZAFE_dict['Na'] = COLZAFE[16]
COLZAFE_dict['UFC'] = COLZAFE[17]
COLZAFE_dict['UFL'] = COLZAFE[18]
COLZAFE_dict['kcal'] = COLZAFE[19]
COLZAFE_dict['Mj'] = COLZAFE[20]
#print(COLZAFE_dict)

COTONEFE = list(np.float_(cotone_farina_estrazione))

COTONEFE_dict = {}
COTONEFE_dict['DM'] = COTONEFE[0]
COTONEFE_dict['PG'] = COTONEFE[1]
COTONEFE_dict['RDP'] = COTONEFE[2]
COTONEFE_dict['RUP'] = COTONEFE[3]
COTONEFE_dict['FG'] = COTONEFE[4]
COTONEFE_dict['NDF'] = COTONEFE[5]
COTONEFE_dict['ADF'] = COTONEFE[6]
COTONEFE_dict['FAT'] = COTONEFE[7]
COTONEFE_dict['ASH'] = COTONEFE[10]
COTONEFE_dict['Ca'] = COTONEFE[11]
COTONEFE_dict['P'] = COTONEFE[12]
COTONEFE_dict['Mg'] = COTONEFE[13]
COTONEFE_dict['K'] = COTONEFE[14]
COTONEFE_dict['S'] = COTONEFE[15]
COTONEFE_dict['Na'] = COTONEFE[16]
COTONEFE_dict['UFC'] = COTONEFE[17]
COTONEFE_dict['UFL'] = COTONEFE[18]
COTONEFE_dict['kcal'] = COTONEFE[19]
COTONEFE_dict['Mj'] = COTONEFE[20]
#print(COTONEFE_dict)

GIRASOLEFE24 = list(np.float_(girasole_farina_estrazione_24x100))

GIRASOLEFE24_dict = {}
GIRASOLEFE24_dict['DM'] = GIRASOLEFE24[0]
GIRASOLEFE24_dict['PG'] = GIRASOLEFE24[1]
GIRASOLEFE24_dict['RDP'] = GIRASOLEFE24[2]
GIRASOLEFE24_dict['RUP'] = GIRASOLEFE24[3]
GIRASOLEFE24_dict['FG'] = GIRASOLEFE24[4]
GIRASOLEFE24_dict['NDF'] = GIRASOLEFE24[5]
GIRASOLEFE24_dict['ADF'] = GIRASOLEFE24[6]
GIRASOLEFE24_dict['FAT'] = GIRASOLEFE24[7]
GIRASOLEFE24_dict['ASH'] = GIRASOLEFE24[10]
GIRASOLEFE24_dict['Ca'] = GIRASOLEFE24[11]
GIRASOLEFE24_dict['P'] = GIRASOLEFE24[12]
GIRASOLEFE24_dict['Mg'] = GIRASOLEFE24[13]
GIRASOLEFE24_dict['K'] = GIRASOLEFE24[14]
GIRASOLEFE24_dict['S'] = GIRASOLEFE24[15]
GIRASOLEFE24_dict['Na'] = GIRASOLEFE24[16]
GIRASOLEFE24_dict['UFC'] = GIRASOLEFE24[17]
GIRASOLEFE24_dict['UFL'] = GIRASOLEFE24[18]
GIRASOLEFE24_dict['kcal'] = GIRASOLEFE24[19]
GIRASOLEFE24_dict['Mj'] = GIRASOLEFE24[20]
#print(GIRASOLEFE24_dict)

GIRASOLEFE34 = list(np.float_(girasole_farina_estrazione_34x100))

GIRASOLEFE34_dict = {}
GIRASOLEFE34_dict['DM'] = GIRASOLEFE34[0]
GIRASOLEFE34_dict['PG'] = GIRASOLEFE34[1]
GIRASOLEFE34_dict['RDP'] = GIRASOLEFE34[2]
GIRASOLEFE34_dict['RUP'] = GIRASOLEFE34[3]
GIRASOLEFE34_dict['FG'] = GIRASOLEFE34[4]
GIRASOLEFE34_dict['NDF'] = GIRASOLEFE34[5]
GIRASOLEFE34_dict['ADF'] = GIRASOLEFE34[6]
GIRASOLEFE34_dict['FAT'] = GIRASOLEFE34[7]
GIRASOLEFE34_dict['ASH'] = GIRASOLEFE34[10]
GIRASOLEFE34_dict['Ca'] = GIRASOLEFE34[11]
GIRASOLEFE34_dict['P'] = GIRASOLEFE34[12]
GIRASOLEFE34_dict['Mg'] = GIRASOLEFE34[13]
GIRASOLEFE34_dict['K'] = GIRASOLEFE34[14]
GIRASOLEFE34_dict['S'] = GIRASOLEFE34[15]
GIRASOLEFE34_dict['Na'] = GIRASOLEFE34[16]
GIRASOLEFE34_dict['UFC'] = GIRASOLEFE34[17]
GIRASOLEFE34_dict['UFL'] = GIRASOLEFE34[18]
GIRASOLEFE34_dict['kcal'] = GIRASOLEFE34[19]
GIRASOLEFE34_dict['Mj'] = GIRASOLEFE34[20]
#print(GIRASOLEFE34_dict)

LINOFE = list(np.float_(lino_farina_estrazione))

LINOFE_dict = {}
LINOFE_dict['DM'] = LINOFE[0]
LINOFE_dict['PG'] = LINOFE[1]
LINOFE_dict['RDP'] = LINOFE[2]
LINOFE_dict['RUP'] = LINOFE[3]
LINOFE_dict['FG'] = LINOFE[4]
LINOFE_dict['NDF'] = LINOFE[5]
LINOFE_dict['ADF'] = LINOFE[6]
LINOFE_dict['FAT'] = LINOFE[7]
LINOFE_dict['ASH'] = LINOFE[10]
LINOFE_dict['Ca'] = LINOFE[11]
LINOFE_dict['P'] = LINOFE[12]
LINOFE_dict['Mg'] = LINOFE[13]
LINOFE_dict['K'] = LINOFE[14]
LINOFE_dict['S'] = LINOFE[15]
LINOFE_dict['Na'] = LINOFE[16]
LINOFE_dict['UFC'] = LINOFE[17]
LINOFE_dict['UFL'] = LINOFE[18]
LINOFE_dict['kcal'] = LINOFE[19]
LINOFE_dict['Mj'] = LINOFE[20]
#print(LINOFE_dict)

SOIAFE45 = list(np.float_(soia_farina_estrazione_45x100))

SOIAFE45_dict = {}
SOIAFE45_dict['DM'] = SOIAFE45[0]
SOIAFE45_dict['PG'] = SOIAFE45[1]
SOIAFE45_dict['RDP'] = SOIAFE45[2]
SOIAFE45_dict['RUP'] = SOIAFE45[3]
SOIAFE45_dict['FG'] = SOIAFE45[4]
SOIAFE45_dict['NDF'] = SOIAFE45[5]
SOIAFE45_dict['ADF'] = SOIAFE45[6]
SOIAFE45_dict['FAT'] = SOIAFE45[7]
SOIAFE45_dict['ASH'] = SOIAFE45[10]
SOIAFE45_dict['Ca'] = SOIAFE45[11]
SOIAFE45_dict['P'] = SOIAFE45[12]
SOIAFE45_dict['Mg'] = SOIAFE45[13]
SOIAFE45_dict['K'] = SOIAFE45[14]
SOIAFE45_dict['S'] = SOIAFE45[15]
SOIAFE45_dict['Na'] = SOIAFE45[16]
SOIAFE45_dict['UFC'] = SOIAFE45[17]
SOIAFE45_dict['UFL'] = SOIAFE45[18]
SOIAFE45_dict['kcal'] = SOIAFE45[19]
SOIAFE45_dict['Mj'] = SOIAFE45[20]
#print(SOIAFE45_dict)

SOIAFE50 = list(np.float_(soia_farina_estrazione_50x100))

SOIAFE50_dict = {}
SOIAFE50_dict['DM'] = SOIAFE50[0]
SOIAFE50_dict['PG'] = SOIAFE50[1]
SOIAFE50_dict['RDP'] = SOIAFE50[2]
SOIAFE50_dict['RUP'] = SOIAFE50[3]
SOIAFE50_dict['FG'] = SOIAFE50[4]
SOIAFE50_dict['NDF'] = SOIAFE50[5]
SOIAFE50_dict['ADF'] = SOIAFE50[6]
SOIAFE50_dict['FAT'] = SOIAFE50[7]
SOIAFE50_dict['ASH'] = SOIAFE50[10]
SOIAFE50_dict['Ca'] = SOIAFE50[11]
SOIAFE50_dict['P'] = SOIAFE50[12]
SOIAFE50_dict['Mg'] = SOIAFE50[13]
SOIAFE50_dict['K'] = SOIAFE50[14]
SOIAFE50_dict['S'] = SOIAFE50[15]
SOIAFE50_dict['Na'] = SOIAFE50[16]
SOIAFE50_dict['UFC'] = SOIAFE50[17]
SOIAFE50_dict['UFL'] = SOIAFE50[18]
SOIAFE50_dict['kcal'] = SOIAFE50[19]
SOIAFE50_dict['Mj'] = SOIAFE50[20]
#print(SOIAFE50_dict)

BIEPOLSECCHE = list(np.float_(bietola_polpe_secche))

BIEPOLSECCHE_dict = {}
BIEPOLSECCHE_dict['DM'] = BIEPOLSECCHE[0]
BIEPOLSECCHE_dict['PG'] = BIEPOLSECCHE[1]
BIEPOLSECCHE_dict['RDP'] = BIEPOLSECCHE[2]
BIEPOLSECCHE_dict['RUP'] = BIEPOLSECCHE[3]
BIEPOLSECCHE_dict['FG'] = BIEPOLSECCHE[4]
BIEPOLSECCHE_dict['NDF'] = BIEPOLSECCHE[5]
BIEPOLSECCHE_dict['ADF'] = BIEPOLSECCHE[6]
BIEPOLSECCHE_dict['FAT'] = BIEPOLSECCHE[7]
BIEPOLSECCHE_dict['ASH'] = BIEPOLSECCHE[10]
BIEPOLSECCHE_dict['Ca'] = BIEPOLSECCHE[11]
BIEPOLSECCHE_dict['P'] = BIEPOLSECCHE[12]
BIEPOLSECCHE_dict['Mg'] = BIEPOLSECCHE[13]
BIEPOLSECCHE_dict['K'] = BIEPOLSECCHE[14]
BIEPOLSECCHE_dict['S'] = BIEPOLSECCHE[15]
BIEPOLSECCHE_dict['Na'] = BIEPOLSECCHE[16]
BIEPOLSECCHE_dict['UFC'] = BIEPOLSECCHE[17]
BIEPOLSECCHE_dict['UFL'] = BIEPOLSECCHE[18]
BIEPOLSECCHE_dict['kcal'] = BIEPOLSECCHE[19]
BIEPOLSECCHE_dict['Mj'] = BIEPOLSECCHE[20]
#print(BIEPOLSECCHE_dict)

BIEPOLSURPRE = list(np.float_(bietola_polpe_surpressate))

BIEPOLSURPRE_dict = {}
BIEPOLSURPRE_dict['DM'] = BIEPOLSURPRE[0]
BIEPOLSURPRE_dict['PG'] = BIEPOLSURPRE[1]
BIEPOLSURPRE_dict['RDP'] = BIEPOLSURPRE[2]
BIEPOLSURPRE_dict['RUP'] = BIEPOLSURPRE[3]
BIEPOLSURPRE_dict['FG'] = BIEPOLSURPRE[4]
BIEPOLSURPRE_dict['NDF'] = BIEPOLSURPRE[5]
BIEPOLSURPRE_dict['ADF'] = BIEPOLSURPRE[6]
BIEPOLSURPRE_dict['FAT'] = BIEPOLSURPRE[7]
BIEPOLSURPRE_dict['ASH'] = BIEPOLSURPRE[10]
BIEPOLSURPRE_dict['Ca'] = BIEPOLSURPRE[11]
BIEPOLSURPRE_dict['P'] = BIEPOLSURPRE[12]
BIEPOLSURPRE_dict['Mg'] = BIEPOLSURPRE[13]
BIEPOLSURPRE_dict['K'] = BIEPOLSURPRE[14]
BIEPOLSURPRE_dict['S'] = BIEPOLSURPRE[15]
BIEPOLSURPRE_dict['Na'] = BIEPOLSURPRE[16]
BIEPOLSURPRE_dict['UFC'] = BIEPOLSURPRE[17]
BIEPOLSURPRE_dict['UFL'] = BIEPOLSURPRE[18]
BIEPOLSURPRE_dict['kcal'] = BIEPOLSURPRE[19]
BIEPOLSURPRE_dict['Mj'] = BIEPOLSURPRE[20]
#print(BIEPOLSURPRE_dict)

CARRUPOLDENO = list(np.float_(carruba_polpa_denocciolata))

CARRUPOLDENO_dict = {}
CARRUPOLDENO_dict['DM'] = CARRUPOLDENO[0]
CARRUPOLDENO_dict['PG'] = CARRUPOLDENO[1]
CARRUPOLDENO_dict['RDP'] = CARRUPOLDENO[2]
CARRUPOLDENO_dict['RUP'] = CARRUPOLDENO[3]
CARRUPOLDENO_dict['FG'] = CARRUPOLDENO[4]
CARRUPOLDENO_dict['NDF'] = CARRUPOLDENO[5]
CARRUPOLDENO_dict['ADF'] = CARRUPOLDENO[6]
CARRUPOLDENO_dict['FAT'] = CARRUPOLDENO[7]
CARRUPOLDENO_dict['ASH'] = CARRUPOLDENO[10]
CARRUPOLDENO_dict['Ca'] = CARRUPOLDENO[11]
CARRUPOLDENO_dict['P'] = CARRUPOLDENO[12]
CARRUPOLDENO_dict['Mg'] = CARRUPOLDENO[13]
CARRUPOLDENO_dict['K'] = CARRUPOLDENO[14]
CARRUPOLDENO_dict['S'] = CARRUPOLDENO[15]
CARRUPOLDENO_dict['Na'] = CARRUPOLDENO[16]
CARRUPOLDENO_dict['UFC'] = CARRUPOLDENO[17]
CARRUPOLDENO_dict['UFL'] = CARRUPOLDENO[18]
CARRUPOLDENO_dict['kcal'] = CARRUPOLDENO[19]
CARRUPOLDENO_dict['Mj'] = CARRUPOLDENO[20]
#print(CARRUPOLDENO_dict)

COTONESEMI = list(np.float_(cotone_semi))

COTONESEMI_dict = {}
COTONESEMI_dict['DM'] = COTONESEMI[0]
COTONESEMI_dict['PG'] = COTONESEMI[1]
COTONESEMI_dict['RDP'] = COTONESEMI[2]
COTONESEMI_dict['RUP'] = COTONESEMI[3]
COTONESEMI_dict['FG'] = COTONESEMI[4]
COTONESEMI_dict['NDF'] = COTONESEMI[5]
COTONESEMI_dict['ADF'] = COTONESEMI[6]
COTONESEMI_dict['FAT'] = COTONESEMI[7]
COTONESEMI_dict['ASH'] = COTONESEMI[10]
COTONESEMI_dict['Ca'] = COTONESEMI[11]
COTONESEMI_dict['P'] = COTONESEMI[12]
COTONESEMI_dict['Mg'] = COTONESEMI[13]
COTONESEMI_dict['K'] = COTONESEMI[14]
COTONESEMI_dict['S'] = COTONESEMI[15]
COTONESEMI_dict['Na'] = COTONESEMI[16]
COTONESEMI_dict['UFC'] = COTONESEMI[17]
COTONESEMI_dict['UFL'] = COTONESEMI[18]
COTONESEMI_dict['kcal'] = COTONESEMI[19]
COTONESEMI_dict['Mj'] = COTONESEMI[20]
#print(COTONESEMI_dict)

CRUSCAFRUDURO = list(np.float_(crusca_frumento_duro))

CRUSCAFRUDURO_dict = {}
CRUSCAFRUDURO_dict['DM'] = CRUSCAFRUDURO[0]
CRUSCAFRUDURO_dict['PG'] = CRUSCAFRUDURO[1]
CRUSCAFRUDURO_dict['RDP'] = CRUSCAFRUDURO[2]
CRUSCAFRUDURO_dict['RUP'] = CRUSCAFRUDURO[3]
CRUSCAFRUDURO_dict['FG'] = CRUSCAFRUDURO[4]
CRUSCAFRUDURO_dict['NDF'] = CRUSCAFRUDURO[5]
CRUSCAFRUDURO_dict['ADF'] = CRUSCAFRUDURO[6]
CRUSCAFRUDURO_dict['FAT'] = CRUSCAFRUDURO[7]
CRUSCAFRUDURO_dict['ASH'] = CRUSCAFRUDURO[10]
CRUSCAFRUDURO_dict['Ca'] = CRUSCAFRUDURO[11]
CRUSCAFRUDURO_dict['P'] = CRUSCAFRUDURO[12]
CRUSCAFRUDURO_dict['Mg'] = CRUSCAFRUDURO[13]
CRUSCAFRUDURO_dict['K'] = CRUSCAFRUDURO[14]
CRUSCAFRUDURO_dict['S'] = CRUSCAFRUDURO[15]
CRUSCAFRUDURO_dict['Na'] = CRUSCAFRUDURO[16]
CRUSCAFRUDURO_dict['UFC'] = CRUSCAFRUDURO[17]
CRUSCAFRUDURO_dict['UFL'] = CRUSCAFRUDURO[18]
CRUSCAFRUDURO_dict['kcal'] = CRUSCAFRUDURO[19]
CRUSCAFRUDURO_dict['Mj'] = CRUSCAFRUDURO[20]
#print(CRUSCAFRUDURO_dict)

CRUFRUTENERO = list(np.float_(crusca_frumento_tenero))

CRUFRUTENERO_dict = {}
CRUFRUTENERO_dict['DM'] = CRUFRUTENERO[0]
CRUFRUTENERO_dict['PG'] = CRUFRUTENERO[1]
CRUFRUTENERO_dict['RDP'] = CRUFRUTENERO[2]
CRUFRUTENERO_dict['RUP'] = CRUFRUTENERO[3]
CRUFRUTENERO_dict['FG'] = CRUFRUTENERO[4]
CRUFRUTENERO_dict['NDF'] = CRUFRUTENERO[5]
CRUFRUTENERO_dict['ADF'] = CRUFRUTENERO[6]
CRUFRUTENERO_dict['FAT'] = CRUFRUTENERO[7]
CRUFRUTENERO_dict['ASH'] = CRUFRUTENERO[10]
CRUFRUTENERO_dict['Ca'] = CRUFRUTENERO[11]
CRUFRUTENERO_dict['P'] = CRUFRUTENERO[12]
CRUFRUTENERO_dict['Mg'] = CRUFRUTENERO[13]
CRUFRUTENERO_dict['K'] = CRUFRUTENERO[14]
CRUFRUTENERO_dict['S'] = CRUFRUTENERO[15]
CRUFRUTENERO_dict['Na'] = CRUFRUTENERO[16]
CRUFRUTENERO_dict['UFC'] = CRUFRUTENERO[17]
CRUFRUTENERO_dict['UFL'] = CRUFRUTENERO[18]
CRUFRUTENERO_dict['kcal'] = CRUFRUTENERO[19]
CRUFRUTENERO_dict['Mj'] = CRUFRUTENERO[20]
#print(CRUFRUTENERO_dict)

CRUSCHELLOFRUDU = list(np.float_(cruschello_frumento_duro))

CRUSCHELLOFRUDU_dict = {}
CRUSCHELLOFRUDU_dict['DM'] = CRUSCHELLOFRUDU[0]
CRUSCHELLOFRUDU_dict['PG'] = CRUSCHELLOFRUDU[1]
CRUSCHELLOFRUDU_dict['RDP'] = CRUSCHELLOFRUDU[2]
CRUSCHELLOFRUDU_dict['RUP'] = CRUSCHELLOFRUDU[3]
CRUSCHELLOFRUDU_dict['FG'] = CRUSCHELLOFRUDU[4]
CRUSCHELLOFRUDU_dict['NDF'] = CRUSCHELLOFRUDU[5]
CRUSCHELLOFRUDU_dict['ADF'] = CRUSCHELLOFRUDU[6]
CRUSCHELLOFRUDU_dict['FAT'] = CRUSCHELLOFRUDU[7]
CRUSCHELLOFRUDU_dict['ASH'] = CRUSCHELLOFRUDU[10]
CRUSCHELLOFRUDU_dict['Ca'] = CRUSCHELLOFRUDU[11]
CRUSCHELLOFRUDU_dict['P'] = CRUSCHELLOFRUDU[12]
CRUSCHELLOFRUDU_dict['Mg'] = CRUSCHELLOFRUDU[13]
CRUSCHELLOFRUDU_dict['K'] = CRUSCHELLOFRUDU[14]
CRUSCHELLOFRUDU_dict['S'] = CRUSCHELLOFRUDU[15]
CRUSCHELLOFRUDU_dict['Na'] = CRUSCHELLOFRUDU[16]
CRUSCHELLOFRUDU_dict['UFC'] = CRUSCHELLOFRUDU[17]
CRUSCHELLOFRUDU_dict['UFL'] = CRUSCHELLOFRUDU[18]
CRUSCHELLOFRUDU_dict['kcal'] = CRUSCHELLOFRUDU[19]
CRUSCHELLOFRUDU_dict['Mj'] = CRUSCHELLOFRUDU[20]
#print(CRUSCHELLOFRUDU_dict)

CRUSCHELLOFRUTE = list(np.float_(cruschello_frumento_tenero))

CRUSCHELLOFRUTE_dict = {}
CRUSCHELLOFRUTE_dict['DM'] = CRUSCHELLOFRUTE[0]
CRUSCHELLOFRUTE_dict['PG'] = CRUSCHELLOFRUTE[1]
CRUSCHELLOFRUTE_dict['RDP'] = CRUSCHELLOFRUTE[2]
CRUSCHELLOFRUTE_dict['RUP'] = CRUSCHELLOFRUTE[3]
CRUSCHELLOFRUTE_dict['FG'] = CRUSCHELLOFRUTE[4]
CRUSCHELLOFRUTE_dict['NDF'] = CRUSCHELLOFRUTE[5]
CRUSCHELLOFRUTE_dict['ADF'] = CRUSCHELLOFRUTE[6]
CRUSCHELLOFRUTE_dict['FAT'] = CRUSCHELLOFRUTE[7]
CRUSCHELLOFRUTE_dict['ASH'] = CRUSCHELLOFRUTE[10]
CRUSCHELLOFRUTE_dict['Ca'] = CRUSCHELLOFRUTE[11]
CRUSCHELLOFRUTE_dict['P'] = CRUSCHELLOFRUTE[12]
CRUSCHELLOFRUTE_dict['Mg'] = CRUSCHELLOFRUTE[13]
CRUSCHELLOFRUTE_dict['K'] = CRUSCHELLOFRUTE[14]
CRUSCHELLOFRUTE_dict['S'] = CRUSCHELLOFRUTE[15]
CRUSCHELLOFRUTE_dict['Na'] = CRUSCHELLOFRUTE[16]
CRUSCHELLOFRUTE_dict['UFC'] = CRUSCHELLOFRUTE[17]
CRUSCHELLOFRUTE_dict['UFL'] = CRUSCHELLOFRUTE[18]
CRUSCHELLOFRUTE_dict['kcal'] = CRUSCHELLOFRUTE[19]
CRUSCHELLOFRUTE_dict['Mj'] = CRUSCHELLOFRUTE[20]
#print(CRUSCHELLOFRUTE_dict)

FRUDUFARINACCIO = list(np.float_(frumento_duro_farinaccio))

FRUDUFARINACCIO_dict = {}
FRUDUFARINACCIO_dict['DM'] = FRUDUFARINACCIO[0]
FRUDUFARINACCIO_dict['PG'] = FRUDUFARINACCIO[1]
FRUDUFARINACCIO_dict['RDP'] = FRUDUFARINACCIO[2]
FRUDUFARINACCIO_dict['RUP'] = FRUDUFARINACCIO[3]
FRUDUFARINACCIO_dict['FG'] = FRUDUFARINACCIO[4]
FRUDUFARINACCIO_dict['NDF'] = FRUDUFARINACCIO[5]
FRUDUFARINACCIO_dict['ADF'] = FRUDUFARINACCIO[6]
FRUDUFARINACCIO_dict['FAT'] = FRUDUFARINACCIO[7]
FRUDUFARINACCIO_dict['ASH'] = FRUDUFARINACCIO[10]
FRUDUFARINACCIO_dict['Ca'] = FRUDUFARINACCIO[11]
FRUDUFARINACCIO_dict['P'] = FRUDUFARINACCIO[12]
FRUDUFARINACCIO_dict['Mg'] = FRUDUFARINACCIO[13]
FRUDUFARINACCIO_dict['K'] = FRUDUFARINACCIO[14]
FRUDUFARINACCIO_dict['S'] = FRUDUFARINACCIO[15]
FRUDUFARINACCIO_dict['Na'] = FRUDUFARINACCIO[16]
FRUDUFARINACCIO_dict['UFC'] = FRUDUFARINACCIO[17]
FRUDUFARINACCIO_dict['UFL'] = FRUDUFARINACCIO[18]
FRUDUFARINACCIO_dict['kcal'] = FRUDUFARINACCIO[19]
FRUDUFARINACCIO_dict['Mj'] = FRUDUFARINACCIO[20]
#print(FRUDUFARINACCIO_dict)

FRUTENEFARINACCIO = list(np.float_(frumento_tenero_farinaccio))

FRUTENEFARINACCIO_dict = {}
FRUTENEFARINACCIO_dict['DM'] = FRUTENEFARINACCIO[0]
FRUTENEFARINACCIO_dict['PG'] = FRUTENEFARINACCIO[1]
FRUTENEFARINACCIO_dict['RDP'] = FRUTENEFARINACCIO[2]
FRUTENEFARINACCIO_dict['RUP'] = FRUTENEFARINACCIO[3]
FRUTENEFARINACCIO_dict['FG'] = FRUTENEFARINACCIO[4]
FRUTENEFARINACCIO_dict['NDF'] = FRUTENEFARINACCIO[5]
FRUTENEFARINACCIO_dict['ADF'] = FRUTENEFARINACCIO[6]
FRUTENEFARINACCIO_dict['FAT'] = FRUTENEFARINACCIO[7]
FRUTENEFARINACCIO_dict['ASH'] = FRUTENEFARINACCIO[10]
FRUTENEFARINACCIO_dict['Ca'] = FRUTENEFARINACCIO[11]
FRUTENEFARINACCIO_dict['P'] = FRUTENEFARINACCIO[12]
FRUTENEFARINACCIO_dict['Mg'] = FRUTENEFARINACCIO[13]
FRUTENEFARINACCIO_dict['K'] = FRUTENEFARINACCIO[14]
FRUTENEFARINACCIO_dict['S'] = FRUTENEFARINACCIO[15]
FRUTENEFARINACCIO_dict['Na'] = FRUTENEFARINACCIO[16]
FRUTENEFARINACCIO_dict['UFC'] = FRUTENEFARINACCIO[17]
FRUTENEFARINACCIO_dict['UFL'] = FRUTENEFARINACCIO[18]
FRUTENEFARINACCIO_dict['kcal'] = FRUTENEFARINACCIO[19]
FRUTENEFARINACCIO_dict['Mj'] = FRUTENEFARINACCIO[20]
#print(FRUTENEFARINACCIO_dict)

FRUMENTOTRI = list(np.float_(frumento_tritello))

FRUMENTOTRI_dict = {}
FRUMENTOTRI_dict['DM'] = FRUMENTOTRI[0]
FRUMENTOTRI_dict['PG'] = FRUMENTOTRI[1]
FRUMENTOTRI_dict['RDP'] = FRUMENTOTRI[2]
FRUMENTOTRI_dict['RUP'] = FRUMENTOTRI[3]
FRUMENTOTRI_dict['FG'] = FRUMENTOTRI[4]
FRUMENTOTRI_dict['NDF'] = FRUMENTOTRI[5]
FRUMENTOTRI_dict['ADF'] = FRUMENTOTRI[6]
FRUMENTOTRI_dict['FAT'] = FRUMENTOTRI[7]
FRUMENTOTRI_dict['ASH'] = FRUMENTOTRI[10]
FRUMENTOTRI_dict['Ca'] = FRUMENTOTRI[11]
FRUMENTOTRI_dict['P'] = FRUMENTOTRI[12]
FRUMENTOTRI_dict['Mg'] = FRUMENTOTRI[13]
FRUMENTOTRI_dict['K'] = FRUMENTOTRI[14]
FRUMENTOTRI_dict['S'] = FRUMENTOTRI[15]
FRUMENTOTRI_dict['Na'] = FRUMENTOTRI[16]
FRUMENTOTRI_dict['UFC'] = FRUMENTOTRI[17]
FRUMENTOTRI_dict['UFL'] = FRUMENTOTRI[18]
FRUMENTOTRI_dict['kcal'] = FRUMENTOTRI[19]
FRUMENTOTRI_dict['Mj'] = FRUMENTOTRI[20]
#print(FRUMENTOTRI_dict)

MAISGLUTINE = list(np.float_(mais_glutine))

MAISGLUTINE_dict = {}
MAISGLUTINE_dict['DM'] = MAISGLUTINE[0]
MAISGLUTINE_dict['PG'] = MAISGLUTINE[1]
MAISGLUTINE_dict['RDP'] = MAISGLUTINE[2]
MAISGLUTINE_dict['RUP'] = MAISGLUTINE[3]
MAISGLUTINE_dict['FG'] = MAISGLUTINE[4]
MAISGLUTINE_dict['NDF'] = MAISGLUTINE[5]
MAISGLUTINE_dict['ADF'] = MAISGLUTINE[6]
MAISGLUTINE_dict['FAT'] = MAISGLUTINE[7]
MAISGLUTINE_dict['ASH'] = MAISGLUTINE[10]
MAISGLUTINE_dict['Ca'] = MAISGLUTINE[11]
MAISGLUTINE_dict['P'] = MAISGLUTINE[12]
MAISGLUTINE_dict['Mg'] = MAISGLUTINE[13]
MAISGLUTINE_dict['K'] = MAISGLUTINE[14]
MAISGLUTINE_dict['S'] = MAISGLUTINE[15]
MAISGLUTINE_dict['Na'] = MAISGLUTINE[16]
MAISGLUTINE_dict['UFC'] = MAISGLUTINE[17]
MAISGLUTINE_dict['UFL'] = MAISGLUTINE[18]
MAISGLUTINE_dict['kcal'] = MAISGLUTINE[19]
MAISGLUTINE_dict['Mj'] = MAISGLUTINE[20]
#print(MAISGLUTINE_dict)

MAISDISTILLERS = list(np.float_(mais_residui_distilleria))

MAISDISTILLERS_dict = {}
MAISDISTILLERS_dict['DM'] = MAISDISTILLERS[0]
MAISDISTILLERS_dict['PG'] = MAISDISTILLERS[1]
MAISDISTILLERS_dict['RDP'] = MAISDISTILLERS[2]
MAISDISTILLERS_dict['RUP'] = MAISDISTILLERS[3]
MAISDISTILLERS_dict['FG'] = MAISDISTILLERS[4]
MAISDISTILLERS_dict['NDF'] = MAISDISTILLERS[5]
MAISDISTILLERS_dict['ADF'] = MAISDISTILLERS[6]
MAISDISTILLERS_dict['FAT'] = MAISDISTILLERS[7]
MAISDISTILLERS_dict['ASH'] = MAISDISTILLERS[10]
MAISDISTILLERS_dict['Ca'] = MAISDISTILLERS[11]
MAISDISTILLERS_dict['P'] = MAISDISTILLERS[12]
MAISDISTILLERS_dict['Mg'] = MAISDISTILLERS[13]
MAISDISTILLERS_dict['K'] = MAISDISTILLERS[14]
MAISDISTILLERS_dict['S'] = MAISDISTILLERS[15]
MAISDISTILLERS_dict['Na'] = MAISDISTILLERS[16]
MAISDISTILLERS_dict['UFC'] = MAISDISTILLERS[17]
MAISDISTILLERS_dict['UFL'] = MAISDISTILLERS[18]
MAISDISTILLERS_dict['kcal'] = MAISDISTILLERS[19]
MAISDISTILLERS_dict['Mj'] = MAISDISTILLERS[20]
#print(MAISDISTILLERS_dict)

MAISSEMOGLU = list(np.float_(mais_semola_glutinata))

MAISSEMOGLU_dict = {}
MAISSEMOGLU_dict['DM'] = MAISSEMOGLU[0]
MAISSEMOGLU_dict['PG'] = MAISSEMOGLU[1]
MAISSEMOGLU_dict['RDP'] = MAISSEMOGLU[2]
MAISSEMOGLU_dict['RUP'] = MAISSEMOGLU[3]
MAISSEMOGLU_dict['FG'] = MAISSEMOGLU[4]
MAISSEMOGLU_dict['NDF'] = MAISSEMOGLU[5]
MAISSEMOGLU_dict['ADF'] = MAISSEMOGLU[6]
MAISSEMOGLU_dict['FAT'] = MAISSEMOGLU[7]
MAISSEMOGLU_dict['ASH'] = MAISSEMOGLU[10]
MAISSEMOGLU_dict['Ca'] = MAISSEMOGLU[11]
MAISSEMOGLU_dict['P'] = MAISSEMOGLU[12]
MAISSEMOGLU_dict['Mg'] = MAISSEMOGLU[13]
MAISSEMOGLU_dict['K'] = MAISSEMOGLU[14]
MAISSEMOGLU_dict['S'] = MAISSEMOGLU[15]
MAISSEMOGLU_dict['Na'] = MAISSEMOGLU[16]
MAISSEMOGLU_dict['UFC'] = MAISSEMOGLU[17]
MAISSEMOGLU_dict['UFL'] = MAISSEMOGLU[18]
MAISSEMOGLU_dict['kcal'] = MAISSEMOGLU[19]
MAISSEMOGLU_dict['Mj'] = MAISSEMOGLU[20]
#print(MAISSEMOGLU_dict)

ORZORADIMALTO = list(np.float_(orzo_radichette_malto))

ORZORADIMALTO_dict = {}
ORZORADIMALTO_dict['DM'] = ORZORADIMALTO[0]
ORZORADIMALTO_dict['PG'] = ORZORADIMALTO[1]
ORZORADIMALTO_dict['RDP'] = ORZORADIMALTO[2]
ORZORADIMALTO_dict['RUP'] = ORZORADIMALTO[3]
ORZORADIMALTO_dict['FG'] = ORZORADIMALTO[4]
ORZORADIMALTO_dict['NDF'] = ORZORADIMALTO[5]
ORZORADIMALTO_dict['ADF'] = ORZORADIMALTO[6]
ORZORADIMALTO_dict['FAT'] = ORZORADIMALTO[7]
ORZORADIMALTO_dict['ASH'] = ORZORADIMALTO[10]
ORZORADIMALTO_dict['Ca'] = ORZORADIMALTO[11]
ORZORADIMALTO_dict['P'] = ORZORADIMALTO[12]
ORZORADIMALTO_dict['Mg'] = ORZORADIMALTO[13]
ORZORADIMALTO_dict['K'] = ORZORADIMALTO[14]
ORZORADIMALTO_dict['S'] = ORZORADIMALTO[15]
ORZORADIMALTO_dict['Na'] = ORZORADIMALTO[16]
ORZORADIMALTO_dict['UFC'] = ORZORADIMALTO[17]
ORZORADIMALTO_dict['UFL'] = ORZORADIMALTO[18]
ORZORADIMALTO_dict['kcal'] = ORZORADIMALTO[19]
ORZORADIMALTO_dict['Mj'] = ORZORADIMALTO[20]
#print(ORZORADIMALTO_dict)

ORZOTREBBIEBI = list(np.float_(orzo_trebbie_birra))

ORZOTREBBIEBI_dict = {}
ORZOTREBBIEBI_dict['DM'] = ORZOTREBBIEBI[0]
ORZOTREBBIEBI_dict['PG'] = ORZOTREBBIEBI[1]
ORZOTREBBIEBI_dict['RDP'] = ORZOTREBBIEBI[2]
ORZOTREBBIEBI_dict['RUP'] = ORZOTREBBIEBI[3]
ORZOTREBBIEBI_dict['FG'] = ORZOTREBBIEBI[4]
ORZOTREBBIEBI_dict['NDF'] = ORZOTREBBIEBI[5]
ORZOTREBBIEBI_dict['ADF'] = ORZOTREBBIEBI[6]
ORZOTREBBIEBI_dict['FAT'] = ORZOTREBBIEBI[7]
ORZOTREBBIEBI_dict['ASH'] = ORZOTREBBIEBI[10]
ORZOTREBBIEBI_dict['Ca'] = ORZOTREBBIEBI[11]
ORZOTREBBIEBI_dict['P'] = ORZOTREBBIEBI[12]
ORZOTREBBIEBI_dict['Mg'] = ORZOTREBBIEBI[13]
ORZOTREBBIEBI_dict['K'] = ORZOTREBBIEBI[14]
ORZOTREBBIEBI_dict['S'] = ORZOTREBBIEBI[15]
ORZOTREBBIEBI_dict['Na'] = ORZOTREBBIEBI[16]
ORZOTREBBIEBI_dict['UFC'] = ORZOTREBBIEBI[17]
ORZOTREBBIEBI_dict['UFL'] = ORZOTREBBIEBI[18]
ORZOTREBBIEBI_dict['kcal'] = ORZOTREBBIEBI[19]
ORZOTREBBIEBI_dict['Mj'] = ORZOTREBBIEBI[20]
#print(ORZOTREBBIEBI_dict)

RISOFARINACCIO = list(np.float_(riso_farinaccio))

RISOFARINACCIO_dict = {}
RISOFARINACCIO_dict['DM'] = RISOFARINACCIO[0]
RISOFARINACCIO_dict['PG'] = RISOFARINACCIO[1]
RISOFARINACCIO_dict['RDP'] = RISOFARINACCIO[2]
RISOFARINACCIO_dict['RUP'] = RISOFARINACCIO[3]
RISOFARINACCIO_dict['FG'] = RISOFARINACCIO[4]
RISOFARINACCIO_dict['NDF'] = RISOFARINACCIO[5]
RISOFARINACCIO_dict['ADF'] = RISOFARINACCIO[6]
RISOFARINACCIO_dict['FAT'] = RISOFARINACCIO[7]
RISOFARINACCIO_dict['ASH'] = RISOFARINACCIO[10]
RISOFARINACCIO_dict['Ca'] = RISOFARINACCIO[11]
RISOFARINACCIO_dict['P'] = RISOFARINACCIO[12]
RISOFARINACCIO_dict['Mg'] = RISOFARINACCIO[13]
RISOFARINACCIO_dict['K'] = RISOFARINACCIO[14]
RISOFARINACCIO_dict['S'] = RISOFARINACCIO[15]
RISOFARINACCIO_dict['Na'] = RISOFARINACCIO[16]
RISOFARINACCIO_dict['UFC'] = RISOFARINACCIO[17]
RISOFARINACCIO_dict['UFL'] = RISOFARINACCIO[18]
RISOFARINACCIO_dict['kcal'] = RISOFARINACCIO[19]
RISOFARINACCIO_dict['Mj'] = RISOFARINACCIO[20]
#print(RISOFARINACCIO_dict)

SOIABUCCETTE = list(np.float_(soia_buccette))

SOIABUCCETTE_dict = {}
SOIABUCCETTE_dict['DM'] = SOIABUCCETTE[0]
SOIABUCCETTE_dict['PG'] = SOIABUCCETTE[1]
SOIABUCCETTE_dict['RDP'] = SOIABUCCETTE[2]
SOIABUCCETTE_dict['RUP'] = SOIABUCCETTE[3]
SOIABUCCETTE_dict['FG'] = SOIABUCCETTE[4]
SOIABUCCETTE_dict['NDF'] = SOIABUCCETTE[5]
SOIABUCCETTE_dict['ADF'] = SOIABUCCETTE[6]
SOIABUCCETTE_dict['FAT'] = SOIABUCCETTE[7]
SOIABUCCETTE_dict['ASH'] = SOIABUCCETTE[10]
SOIABUCCETTE_dict['Ca'] = SOIABUCCETTE[11]
SOIABUCCETTE_dict['P'] = SOIABUCCETTE[12]
SOIABUCCETTE_dict['Mg'] = SOIABUCCETTE[13]
SOIABUCCETTE_dict['K'] = SOIABUCCETTE[14]
SOIABUCCETTE_dict['S'] = SOIABUCCETTE[15]
SOIABUCCETTE_dict['Na'] = SOIABUCCETTE[16]
SOIABUCCETTE_dict['UFC'] = SOIABUCCETTE[17]
SOIABUCCETTE_dict['UFL'] = SOIABUCCETTE[18]
SOIABUCCETTE_dict['kcal'] = SOIABUCCETTE[19]
SOIABUCCETTE_dict['Mj'] = SOIABUCCETTE[20]
#print(SOIABUCCETTE_dict)

FAVINO = list(np.float_(favino))

FAVINO_dict = {}
FAVINO_dict['DM'] = FAVINO[0]
FAVINO_dict['PG'] = FAVINO[1]
FAVINO_dict['RDP'] = FAVINO[2]
FAVINO_dict['RUP'] = FAVINO[3]
FAVINO_dict['FG'] = FAVINO[4]
FAVINO_dict['NDF'] = FAVINO[5]
FAVINO_dict['ADF'] = FAVINO[6]
FAVINO_dict['FAT'] = FAVINO[7]
FAVINO_dict['ASH'] = FAVINO[10]
FAVINO_dict['Ca'] = FAVINO[11]
FAVINO_dict['P'] = FAVINO[12]
FAVINO_dict['Mg'] = FAVINO[13]
FAVINO_dict['K'] = FAVINO[14]
FAVINO_dict['S'] = FAVINO[15]
FAVINO_dict['Na'] = FAVINO[16]
FAVINO_dict['UFC'] = FAVINO[17]
FAVINO_dict['UFL'] = FAVINO[18]
FAVINO_dict['kcal'] = FAVINO[19]
FAVINO_dict['Mj'] = FAVINO[20]
#print(FAVINO_dict)

LUPINO = list(np.float_(lupino))

LUPINO_dict = {}
LUPINO_dict['DM'] = LUPINO[0]
LUPINO_dict['PG'] = LUPINO[1]
LUPINO_dict['RDP'] = LUPINO[2]
LUPINO_dict['RUP'] = LUPINO[3]
LUPINO_dict['FG'] = LUPINO[4]
LUPINO_dict['NDF'] = LUPINO[5]
LUPINO_dict['ADF'] = LUPINO[6]
LUPINO_dict['FAT'] = LUPINO[7]
LUPINO_dict['ASH'] = LUPINO[10]
LUPINO_dict['Ca'] = LUPINO[11]
LUPINO_dict['P'] = LUPINO[12]
LUPINO_dict['Mg'] = LUPINO[13]
LUPINO_dict['K'] = LUPINO[14]
LUPINO_dict['S'] = LUPINO[15]
LUPINO_dict['Na'] = LUPINO[16]
LUPINO_dict['UFC'] = LUPINO[17]
LUPINO_dict['UFL'] = LUPINO[18]
LUPINO_dict['kcal'] = LUPINO[19]
LUPINO_dict['Mj'] = LUPINO[20]
#print(LUPINO_dict)

PISELLO = list(np.float_(pisello))

PISELLO_dict = {}
PISELLO_dict['DM'] = PISELLO[0]
PISELLO_dict['PG'] = PISELLO[1]
PISELLO_dict['RDP'] = PISELLO[2]
PISELLO_dict['RUP'] = PISELLO[3]
PISELLO_dict['FG'] = PISELLO[4]
PISELLO_dict['NDF'] = PISELLO[5]
PISELLO_dict['ADF'] = PISELLO[6]
PISELLO_dict['FAT'] = PISELLO[7]
PISELLO_dict['ASH'] = PISELLO[10]
PISELLO_dict['Ca'] = PISELLO[11]
PISELLO_dict['P'] = PISELLO[12]
PISELLO_dict['Mg'] = PISELLO[13]
PISELLO_dict['K'] = PISELLO[14]
PISELLO_dict['S'] = PISELLO[15]
PISELLO_dict['Na'] = PISELLO[16]
PISELLO_dict['UFC'] = PISELLO[17]
PISELLO_dict['UFL'] = PISELLO[18]
PISELLO_dict['kcal'] = PISELLO[19]
PISELLO_dict['Mj'] = PISELLO[20]
#print(PISELLO_dict)

SOIAINTEGRALE = list(np.float_(soia_integrale))

SOIAINTEGRALE_dict = {}
SOIAINTEGRALE_dict['DM'] = SOIAINTEGRALE[0]
SOIAINTEGRALE_dict['PG'] = SOIAINTEGRALE[1]
SOIAINTEGRALE_dict['RDP'] = SOIAINTEGRALE[2]
SOIAINTEGRALE_dict['RUP'] = SOIAINTEGRALE[3]
SOIAINTEGRALE_dict['FG'] = SOIAINTEGRALE[4]
SOIAINTEGRALE_dict['NDF'] = SOIAINTEGRALE[5]
SOIAINTEGRALE_dict['ADF'] = SOIAINTEGRALE[6]
SOIAINTEGRALE_dict['FAT'] = SOIAINTEGRALE[7]
SOIAINTEGRALE_dict['ASH'] = SOIAINTEGRALE[10]
SOIAINTEGRALE_dict['Ca'] = SOIAINTEGRALE[11]
SOIAINTEGRALE_dict['P'] = SOIAINTEGRALE[12]
SOIAINTEGRALE_dict['Mg'] = SOIAINTEGRALE[13]
SOIAINTEGRALE_dict['K'] = SOIAINTEGRALE[14]
SOIAINTEGRALE_dict['S'] = SOIAINTEGRALE[15]
SOIAINTEGRALE_dict['Na'] = SOIAINTEGRALE[16]
SOIAINTEGRALE_dict['UFC'] = SOIAINTEGRALE[17]
SOIAINTEGRALE_dict['UFL'] = SOIAINTEGRALE[18]
SOIAINTEGRALE_dict['kcal'] = SOIAINTEGRALE[19]
SOIAINTEGRALE_dict['Mj'] = SOIAINTEGRALE[20]
#print(SOIAINTEGRALE_dict)

AGRUMIPASTAZZO = list(np.float_(agrumi_pastazzo_secco))

AGRUMIPASTAZZO_dict = {}
AGRUMIPASTAZZO_dict['DM'] = AGRUMIPASTAZZO[0]
AGRUMIPASTAZZO_dict['PG'] = AGRUMIPASTAZZO[1]
AGRUMIPASTAZZO_dict['RDP'] = AGRUMIPASTAZZO[2]
AGRUMIPASTAZZO_dict['RUP'] = AGRUMIPASTAZZO[3]
AGRUMIPASTAZZO_dict['FG'] = AGRUMIPASTAZZO[4]
AGRUMIPASTAZZO_dict['NDF'] = AGRUMIPASTAZZO[5]
AGRUMIPASTAZZO_dict['ADF'] = AGRUMIPASTAZZO[6]
AGRUMIPASTAZZO_dict['FAT'] = AGRUMIPASTAZZO[7]
AGRUMIPASTAZZO_dict['ASH'] = AGRUMIPASTAZZO[10]
AGRUMIPASTAZZO_dict['Ca'] = AGRUMIPASTAZZO[11]
AGRUMIPASTAZZO_dict['P'] = AGRUMIPASTAZZO[12]
AGRUMIPASTAZZO_dict['Mg'] = AGRUMIPASTAZZO[13]
AGRUMIPASTAZZO_dict['K'] = AGRUMIPASTAZZO[14]
AGRUMIPASTAZZO_dict['S'] = AGRUMIPASTAZZO[15]
AGRUMIPASTAZZO_dict['Na'] = AGRUMIPASTAZZO[16]
AGRUMIPASTAZZO_dict['UFC'] = AGRUMIPASTAZZO[17]
AGRUMIPASTAZZO_dict['UFL'] = AGRUMIPASTAZZO[18]
AGRUMIPASTAZZO_dict['kcal'] = AGRUMIPASTAZZO[19]
AGRUMIPASTAZZO_dict['Mj'] = AGRUMIPASTAZZO[20]
#print(AGRUMIPASTAZZO_dict)

BIRRALIEVITO = list(np.float_(birra_lievito))

BIRRALIEVITO_dict = {}
BIRRALIEVITO_dict['DM'] = BIRRALIEVITO[0]
BIRRALIEVITO_dict['PG'] = BIRRALIEVITO[1]
BIRRALIEVITO_dict['RDP'] = BIRRALIEVITO[2]
BIRRALIEVITO_dict['RUP'] = BIRRALIEVITO[3]
BIRRALIEVITO_dict['FG'] = BIRRALIEVITO[4]
BIRRALIEVITO_dict['NDF'] = BIRRALIEVITO[5]
BIRRALIEVITO_dict['ADF'] = BIRRALIEVITO[6]
BIRRALIEVITO_dict['FAT'] = BIRRALIEVITO[7]
BIRRALIEVITO_dict['ASH'] = BIRRALIEVITO[10]
BIRRALIEVITO_dict['Ca'] = BIRRALIEVITO[11]
BIRRALIEVITO_dict['P'] = BIRRALIEVITO[12]
BIRRALIEVITO_dict['Mg'] = BIRRALIEVITO[13]
BIRRALIEVITO_dict['K'] = BIRRALIEVITO[14]
BIRRALIEVITO_dict['S'] = BIRRALIEVITO[15]
BIRRALIEVITO_dict['Na'] = BIRRALIEVITO[16]
BIRRALIEVITO_dict['UFC'] = BIRRALIEVITO[17]
BIRRALIEVITO_dict['UFL'] = BIRRALIEVITO[18]
BIRRALIEVITO_dict['kcal'] = BIRRALIEVITO[19]
BIRRALIEVITO_dict['Mj'] = BIRRALIEVITO[20]
#print(BIRRALIEVITO_dict)

CALCIOSAPONI = list(np.float_(calcio_saponi))

CALCIOSAPONI_dict = {}
CALCIOSAPONI_dict['DM'] = CALCIOSAPONI[0]
CALCIOSAPONI_dict['PG'] = CALCIOSAPONI[1]
CALCIOSAPONI_dict['RDP'] = CALCIOSAPONI[2]
CALCIOSAPONI_dict['RUP'] = CALCIOSAPONI[3]
CALCIOSAPONI_dict['FG'] = CALCIOSAPONI[4]
CALCIOSAPONI_dict['NDF'] = CALCIOSAPONI[5]
CALCIOSAPONI_dict['ADF'] = CALCIOSAPONI[6]
CALCIOSAPONI_dict['FAT'] = CALCIOSAPONI[7]
CALCIOSAPONI_dict['ASH'] = CALCIOSAPONI[10]
CALCIOSAPONI_dict['Ca'] = CALCIOSAPONI[11]
CALCIOSAPONI_dict['P'] = CALCIOSAPONI[12]
CALCIOSAPONI_dict['Mg'] = CALCIOSAPONI[13]
CALCIOSAPONI_dict['K'] = CALCIOSAPONI[14]
CALCIOSAPONI_dict['S'] = CALCIOSAPONI[15]
CALCIOSAPONI_dict['Na'] = CALCIOSAPONI[16]
CALCIOSAPONI_dict['UFC'] = CALCIOSAPONI[17]
CALCIOSAPONI_dict['UFL'] = CALCIOSAPONI[18]
CALCIOSAPONI_dict['kcal'] = CALCIOSAPONI[19]
CALCIOSAPONI_dict['Mj'] = CALCIOSAPONI[20]
#print(CALCIOSAPONI_dict)

COCCOPANNELLO = list(np.float_(cocco_pannello))

COCCOPANNELLO_dict = {}
COCCOPANNELLO_dict['DM'] = COCCOPANNELLO[0]
COCCOPANNELLO_dict['PG'] = COCCOPANNELLO[1]
COCCOPANNELLO_dict['RDP'] = COCCOPANNELLO[2]
COCCOPANNELLO_dict['RUP'] = COCCOPANNELLO[3]
COCCOPANNELLO_dict['FG'] = COCCOPANNELLO[4]
COCCOPANNELLO_dict['NDF'] = COCCOPANNELLO[5]
COCCOPANNELLO_dict['ADF'] = COCCOPANNELLO[6]
COCCOPANNELLO_dict['FAT'] = COCCOPANNELLO[7]
COCCOPANNELLO_dict['ASH'] = COCCOPANNELLO[10]
COCCOPANNELLO_dict['Ca'] = COCCOPANNELLO[11]
COCCOPANNELLO_dict['P'] = COCCOPANNELLO[12]
COCCOPANNELLO_dict['Mg'] = COCCOPANNELLO[13]
COCCOPANNELLO_dict['K'] = COCCOPANNELLO[14]
COCCOPANNELLO_dict['S'] = COCCOPANNELLO[15]
COCCOPANNELLO_dict['Na'] = COCCOPANNELLO[16]
COCCOPANNELLO_dict['UFC'] = COCCOPANNELLO[17]
COCCOPANNELLO_dict['UFL'] = COCCOPANNELLO[18]
COCCOPANNELLO_dict['kcal'] = COCCOPANNELLO[19]
COCCOPANNELLO_dict['Mj'] = COCCOPANNELLO[20]
#print(COCCOPANNELLO_dict)

FRUTEGERME = list(np.float_(frumento_tenero_germe))

FRUTEGERME_dict = {}
FRUTEGERME_dict['DM'] = FRUTEGERME[0]
FRUTEGERME_dict['PG'] = FRUTEGERME[1]
FRUTEGERME_dict['RDP'] = FRUTEGERME[2]
FRUTEGERME_dict['RUP'] = FRUTEGERME[3]
FRUTEGERME_dict['FG'] = FRUTEGERME[4]
FRUTEGERME_dict['NDF'] = FRUTEGERME[5]
FRUTEGERME_dict['ADF'] = FRUTEGERME[6]
FRUTEGERME_dict['FAT'] = FRUTEGERME[7]
FRUTEGERME_dict['ASH'] = FRUTEGERME[10]
FRUTEGERME_dict['Ca'] = FRUTEGERME[11]
FRUTEGERME_dict['P'] = FRUTEGERME[12]
FRUTEGERME_dict['Mg'] = FRUTEGERME[13]
FRUTEGERME_dict['K'] = FRUTEGERME[14]
FRUTEGERME_dict['S'] = FRUTEGERME[15]
FRUTEGERME_dict['Na'] = FRUTEGERME[16]
FRUTEGERME_dict['UFC'] = FRUTEGERME[17]
FRUTEGERME_dict['UFL'] = FRUTEGERME[18]
FRUTEGERME_dict['kcal'] = FRUTEGERME[19]
FRUTEGERME_dict['Mj'] = FRUTEGERME[20]
#print(FRUTEGERME_dict)

LATTEMAPOL = list(np.float_(latte_magro_polvere))

LATTEMAPOL_dict = {}
LATTEMAPOL_dict['DM'] = LATTEMAPOL[0]
LATTEMAPOL_dict['PG'] = LATTEMAPOL[1]
LATTEMAPOL_dict['RDP'] = LATTEMAPOL[2]
LATTEMAPOL_dict['RUP'] = LATTEMAPOL[3]
LATTEMAPOL_dict['FG'] = LATTEMAPOL[4]
LATTEMAPOL_dict['NDF'] = LATTEMAPOL[5]
LATTEMAPOL_dict['ADF'] = LATTEMAPOL[6]
LATTEMAPOL_dict['FAT'] = LATTEMAPOL[7]
LATTEMAPOL_dict['ASH'] = LATTEMAPOL[10]
LATTEMAPOL_dict['Ca'] = LATTEMAPOL[11]
LATTEMAPOL_dict['P'] = LATTEMAPOL[12]
LATTEMAPOL_dict['Mg'] = LATTEMAPOL[13]
LATTEMAPOL_dict['K'] = LATTEMAPOL[14]
LATTEMAPOL_dict['S'] = LATTEMAPOL[15]
LATTEMAPOL_dict['Na'] = LATTEMAPOL[16]
LATTEMAPOL_dict['UFC'] = LATTEMAPOL[17]
LATTEMAPOL_dict['UFL'] = LATTEMAPOL[18]
LATTEMAPOL_dict['kcal'] = LATTEMAPOL[19]
LATTEMAPOL_dict['Mj'] = LATTEMAPOL[20]
#print(LATTEMAPOL_dict)

LATTESIERO = list(np.float_(latte_siero))

LATTESIERO_dict = {}
LATTESIERO_dict['DM'] = LATTESIERO[0]
LATTESIERO_dict['PG'] = LATTESIERO[1]
LATTESIERO_dict['RDP'] = LATTESIERO[2]
LATTESIERO_dict['RUP'] = LATTESIERO[3]
LATTESIERO_dict['FG'] = LATTESIERO[4]
LATTESIERO_dict['NDF'] = LATTESIERO[5]
LATTESIERO_dict['ADF'] = LATTESIERO[6]
LATTESIERO_dict['FAT'] = LATTESIERO[7]
LATTESIERO_dict['ASH'] = LATTESIERO[10]
LATTESIERO_dict['Ca'] = LATTESIERO[11]
LATTESIERO_dict['P'] = LATTESIERO[12]
LATTESIERO_dict['Mg'] = LATTESIERO[13]
LATTESIERO_dict['K'] = LATTESIERO[14]
LATTESIERO_dict['S'] = LATTESIERO[15]
LATTESIERO_dict['Na'] = LATTESIERO[16]
LATTESIERO_dict['UFC'] = LATTESIERO[17]
LATTESIERO_dict['UFL'] = LATTESIERO[18]
LATTESIERO_dict['kcal'] = LATTESIERO[19]
LATTESIERO_dict['Mj'] = LATTESIERO[20]
#print(LATTESIERO_dict)

MANIOCA = list(np.float_(manioca))

MANIOCA_dict = {}
MANIOCA_dict['DM'] = MANIOCA[0]
MANIOCA_dict['PG'] = MANIOCA[1]
MANIOCA_dict['RDP'] = MANIOCA[2]
MANIOCA_dict['RUP'] = MANIOCA[3]
MANIOCA_dict['FG'] = MANIOCA[4]
MANIOCA_dict['NDF'] = MANIOCA[5]
MANIOCA_dict['ADF'] = MANIOCA[6]
MANIOCA_dict['FAT'] = MANIOCA[7]
MANIOCA_dict['ASH'] = MANIOCA[10]
MANIOCA_dict['Ca'] = MANIOCA[11]
MANIOCA_dict['P'] = MANIOCA[12]
MANIOCA_dict['Mg'] = MANIOCA[13]
MANIOCA_dict['K'] = MANIOCA[14]
MANIOCA_dict['S'] = MANIOCA[15]
MANIOCA_dict['Na'] = MANIOCA[16]
MANIOCA_dict['UFC'] = MANIOCA[17]
MANIOCA_dict['UFL'] = MANIOCA[18]
MANIOCA_dict['kcal'] = MANIOCA[19]
MANIOCA_dict['Mj'] = MANIOCA[20]
#print(MANIOCA_dict)

MELASSOBARBA = list(np.float_(melasso_barbabietola))

MELASSOBARBA_dict = {}
MELASSOBARBA_dict['DM'] = MELASSOBARBA[0]
MELASSOBARBA_dict['PG'] = MELASSOBARBA[1]
MELASSOBARBA_dict['RDP'] = MELASSOBARBA[2]
MELASSOBARBA_dict['RUP'] = MELASSOBARBA[3]
MELASSOBARBA_dict['FG'] = MELASSOBARBA[4]
MELASSOBARBA_dict['NDF'] = MELASSOBARBA[5]
MELASSOBARBA_dict['ADF'] = MELASSOBARBA[6]
MELASSOBARBA_dict['FAT'] = MELASSOBARBA[7]
MELASSOBARBA_dict['ASH'] = MELASSOBARBA[10]
MELASSOBARBA_dict['Ca'] = MELASSOBARBA[11]
MELASSOBARBA_dict['P'] = MELASSOBARBA[12]
MELASSOBARBA_dict['Mg'] = MELASSOBARBA[13]
MELASSOBARBA_dict['K'] = MELASSOBARBA[14]
MELASSOBARBA_dict['S'] = MELASSOBARBA[15]
MELASSOBARBA_dict['Na'] = MELASSOBARBA[16]
MELASSOBARBA_dict['UFC'] = MELASSOBARBA[17]
MELASSOBARBA_dict['UFL'] = MELASSOBARBA[18]
MELASSOBARBA_dict['kcal'] = MELASSOBARBA[19]
MELASSOBARBA_dict['Mj'] = MELASSOBARBA[20]
#print(MELASSOBARBA_dict)

MELASSOCANNA = list(np.float_(melasso_canna))

MELASSOCANNA_dict = {}
MELASSOCANNA_dict['DM'] = MELASSOCANNA[0]
MELASSOCANNA_dict['PG'] = MELASSOCANNA[1]
MELASSOCANNA_dict['RDP'] = MELASSOCANNA[2]
MELASSOCANNA_dict['RUP'] = MELASSOCANNA[3]
MELASSOCANNA_dict['FG'] = MELASSOCANNA[4]
MELASSOCANNA_dict['NDF'] = MELASSOCANNA[5]
MELASSOCANNA_dict['ADF'] = MELASSOCANNA[6]
MELASSOCANNA_dict['FAT'] = MELASSOCANNA[7]
MELASSOCANNA_dict['ASH'] = MELASSOCANNA[10]
MELASSOCANNA_dict['Ca'] = MELASSOCANNA[11]
MELASSOCANNA_dict['P'] = MELASSOCANNA[12]
MELASSOCANNA_dict['Mg'] = MELASSOCANNA[13]
MELASSOCANNA_dict['K'] = MELASSOCANNA[14]
MELASSOCANNA_dict['S'] = MELASSOCANNA[15]
MELASSOCANNA_dict['Na'] = MELASSOCANNA[16]
MELASSOCANNA_dict['UFC'] = MELASSOCANNA[17]
MELASSOCANNA_dict['UFL'] = MELASSOCANNA[18]
MELASSOCANNA_dict['kcal'] = MELASSOCANNA[19]
MELASSOCANNA_dict['Mj'] = MELASSOCANNA[20]
#print(MELASSOCANNA_dict)

PATATEESSI = list(np.float_(patate_essiccate))

PATATEESSI_dict = {}
PATATEESSI_dict['DM'] = PATATEESSI[0]
PATATEESSI_dict['PG'] = PATATEESSI[1]
PATATEESSI_dict['RDP'] = PATATEESSI[2]
PATATEESSI_dict['RUP'] = PATATEESSI[3]
PATATEESSI_dict['FG'] = PATATEESSI[4]
PATATEESSI_dict['NDF'] = PATATEESSI[5]
PATATEESSI_dict['ADF'] = PATATEESSI[6]
PATATEESSI_dict['FAT'] = PATATEESSI[7]
PATATEESSI_dict['ASH'] = PATATEESSI[10]
PATATEESSI_dict['Ca'] = PATATEESSI[11]
PATATEESSI_dict['P'] = PATATEESSI[12]
PATATEESSI_dict['Mg'] = PATATEESSI[13]
PATATEESSI_dict['K'] = PATATEESSI[14]
PATATEESSI_dict['S'] = PATATEESSI[15]
PATATEESSI_dict['Na'] = PATATEESSI[16]
PATATEESSI_dict['UFC'] = PATATEESSI[17]
PATATEESSI_dict['UFL'] = PATATEESSI[18]
PATATEESSI_dict['kcal'] = PATATEESSI[19]
PATATEESSI_dict['Mj'] = PATATEESSI[20]
#print(PATATEESSI_dict)

PROTEINAPATA = list(np.float_(proteina_patata))

PROTEINAPATA_dict = {}
PROTEINAPATA_dict['DM'] = PROTEINAPATA[0]
PROTEINAPATA_dict['PG'] = PROTEINAPATA[1]
PROTEINAPATA_dict['RDP'] = PROTEINAPATA[2]
PROTEINAPATA_dict['RUP'] = PROTEINAPATA[3]
PROTEINAPATA_dict['FG'] = PROTEINAPATA[4]
PROTEINAPATA_dict['NDF'] = PROTEINAPATA[5]
PROTEINAPATA_dict['ADF'] = PROTEINAPATA[6]
PROTEINAPATA_dict['FAT'] = PROTEINAPATA[7]
PROTEINAPATA_dict['ASH'] = PROTEINAPATA[10]
PROTEINAPATA_dict['Ca'] = PROTEINAPATA[11]
PROTEINAPATA_dict['P'] = PROTEINAPATA[12]
PROTEINAPATA_dict['Mg'] = PROTEINAPATA[13]
PROTEINAPATA_dict['K'] = PROTEINAPATA[14]
PROTEINAPATA_dict['S'] = PROTEINAPATA[15]
PROTEINAPATA_dict['Na'] = PROTEINAPATA[16]
PROTEINAPATA_dict['UFC'] = PROTEINAPATA[17]
PROTEINAPATA_dict['UFL'] = PROTEINAPATA[18]
PROTEINAPATA_dict['kcal'] = PROTEINAPATA[19]
PROTEINAPATA_dict['Mj'] = PROTEINAPATA[20]
#print(PROTEINAPATA_dict)

RISOGEMMA = list(np.float_(riso_gemma))

RISOGEMMA_dict = {}
RISOGEMMA_dict['DM'] = RISOGEMMA[0]
RISOGEMMA_dict['PG'] = RISOGEMMA[1]
RISOGEMMA_dict['RDP'] = RISOGEMMA[2]
RISOGEMMA_dict['RUP'] = RISOGEMMA[3]
RISOGEMMA_dict['FG'] = RISOGEMMA[4]
RISOGEMMA_dict['NDF'] = RISOGEMMA[5]
RISOGEMMA_dict['ADF'] = RISOGEMMA[6]
RISOGEMMA_dict['FAT'] = RISOGEMMA[7]
RISOGEMMA_dict['ASH'] = RISOGEMMA[10]
RISOGEMMA_dict['Ca'] = RISOGEMMA[11]
RISOGEMMA_dict['P'] = RISOGEMMA[12]
RISOGEMMA_dict['Mg'] = RISOGEMMA[13]
RISOGEMMA_dict['K'] = RISOGEMMA[14]
RISOGEMMA_dict['S'] = RISOGEMMA[15]
RISOGEMMA_dict['Na'] = RISOGEMMA[16]
RISOGEMMA_dict['UFC'] = RISOGEMMA[17]
RISOGEMMA_dict['UFL'] = RISOGEMMA[18]
RISOGEMMA_dict['kcal'] = RISOGEMMA[19]
RISOGEMMA_dict['Mj'] = RISOGEMMA[20]
#print(RISOGEMMA_dict)

RISOGRANAVER = list(np.float_(riso_grana_verde))

RISOGRANAVER_dict = {}
RISOGRANAVER_dict['DM'] = RISOGRANAVER[0]
RISOGRANAVER_dict['PG'] = RISOGRANAVER[1]
RISOGRANAVER_dict['RDP'] = RISOGRANAVER[2]
RISOGRANAVER_dict['RUP'] = RISOGRANAVER[3]
RISOGRANAVER_dict['FG'] = RISOGRANAVER[4]
RISOGRANAVER_dict['NDF'] = RISOGRANAVER[5]
RISOGRANAVER_dict['ADF'] = RISOGRANAVER[6]
RISOGRANAVER_dict['FAT'] = RISOGRANAVER[7]
RISOGRANAVER_dict['ASH'] = RISOGRANAVER[10]
RISOGRANAVER_dict['Ca'] = RISOGRANAVER[11]
RISOGRANAVER_dict['P'] = RISOGRANAVER[12]
RISOGRANAVER_dict['Mg'] = RISOGRANAVER[13]
RISOGRANAVER_dict['K'] = RISOGRANAVER[14]
RISOGRANAVER_dict['S'] = RISOGRANAVER[15]
RISOGRANAVER_dict['Na'] = RISOGRANAVER[16]
RISOGRANAVER_dict['UFC'] = RISOGRANAVER[17]
RISOGRANAVER_dict['UFL'] = RISOGRANAVER[18]
RISOGRANAVER_dict['kcal'] = RISOGRANAVER[19]
RISOGRANAVER_dict['Mj'] = RISOGRANAVER[20]
#print(RISOGRANAVER_dict)

RISOPULACOMM = list(np.float_(riso_pula_commerciale))

RISOPULACOMM_dict = {}
RISOPULACOMM_dict['DM'] = RISOPULACOMM[0]
RISOPULACOMM_dict['PG'] = RISOPULACOMM[1]
RISOPULACOMM_dict['RDP'] = RISOPULACOMM[2]
RISOPULACOMM_dict['RUP'] = RISOPULACOMM[3]
RISOPULACOMM_dict['FG'] = RISOPULACOMM[4]
RISOPULACOMM_dict['NDF'] = RISOPULACOMM[5]
RISOPULACOMM_dict['ADF'] = RISOPULACOMM[6]
RISOPULACOMM_dict['FAT'] = RISOPULACOMM[7]
RISOPULACOMM_dict['ASH'] = RISOPULACOMM[10]
RISOPULACOMM_dict['Ca'] = RISOPULACOMM[11]
RISOPULACOMM_dict['P'] = RISOPULACOMM[12]
RISOPULACOMM_dict['Mg'] = RISOPULACOMM[13]
RISOPULACOMM_dict['K'] = RISOPULACOMM[14]
RISOPULACOMM_dict['S'] = RISOPULACOMM[15]
RISOPULACOMM_dict['Na'] = RISOPULACOMM[16]
RISOPULACOMM_dict['UFC'] = RISOPULACOMM[17]
RISOPULACOMM_dict['UFL'] = RISOPULACOMM[18]
RISOPULACOMM_dict['kcal'] = RISOPULACOMM[19]
RISOPULACOMM_dict['Mj'] = RISOPULACOMM[20]
#print(RISOPULACOMM_dict)

RISOPULAVERG = list(np.float_(riso_pula_vergine))

RISOPULAVERG_dict = {}
RISOPULAVERG_dict['DM'] = RISOPULAVERG[0]
RISOPULAVERG_dict['PG'] = RISOPULAVERG[1]
RISOPULAVERG_dict['RDP'] = RISOPULAVERG[2]
RISOPULAVERG_dict['RUP'] = RISOPULAVERG[3]
RISOPULAVERG_dict['FG'] = RISOPULAVERG[4]
RISOPULAVERG_dict['NDF'] = RISOPULAVERG[5]
RISOPULAVERG_dict['ADF'] = RISOPULAVERG[6]
RISOPULAVERG_dict['FAT'] = RISOPULAVERG[7]
RISOPULAVERG_dict['ASH'] = RISOPULAVERG[10]
RISOPULAVERG_dict['Ca'] = RISOPULAVERG[11]
RISOPULAVERG_dict['P'] = RISOPULAVERG[12]
RISOPULAVERG_dict['Mg'] = RISOPULAVERG[13]
RISOPULAVERG_dict['K'] = RISOPULAVERG[14]
RISOPULAVERG_dict['S'] = RISOPULAVERG[15]
RISOPULAVERG_dict['Na'] = RISOPULAVERG[16]
RISOPULAVERG_dict['UFC'] = RISOPULAVERG[17]
RISOPULAVERG_dict['UFL'] = RISOPULAVERG[18]
RISOPULAVERG_dict['kcal'] = RISOPULAVERG[19]
RISOPULAVERG_dict['Mj'] = RISOPULAVERG[20]
#print(RISOPULAVERG_dict)

RISOROTT = list(np.float_(riso_rottura))

RISOROTT_dict = {}
RISOROTT_dict['DM'] = RISOROTT[0]
RISOROTT_dict['PG'] = RISOROTT[1]
RISOROTT_dict['RDP'] = RISOROTT[2]
RISOROTT_dict['RUP'] = RISOROTT[3]
RISOROTT_dict['FG'] = RISOROTT[4]
RISOROTT_dict['NDF'] = RISOROTT[5]
RISOROTT_dict['ADF'] = RISOROTT[6]
RISOROTT_dict['FAT'] = RISOROTT[7]
RISOROTT_dict['ASH'] = RISOROTT[10]
RISOROTT_dict['Ca'] = RISOROTT[11]
RISOROTT_dict['P'] = RISOROTT[12]
RISOROTT_dict['Mg'] = RISOROTT[13]
RISOROTT_dict['K'] = RISOROTT[14]
RISOROTT_dict['S'] = RISOROTT[15]
RISOROTT_dict['Na'] = RISOROTT[16]
RISOROTT_dict['UFC'] = RISOROTT[17]
RISOROTT_dict['UFL'] = RISOROTT[18]
RISOROTT_dict['kcal'] = RISOROTT[19]
RISOROTT_dict['Mj'] = RISOROTT[20]
#print(RISOROTT_dict)


alimenti = {'erba_loietto': ERBALOIETTO_dict, 'erba_medica_disidratata_15x100': ERBAMEDICADIS15_dict, 'erba_medica_disidratata_17x100': ERBAMEDICADIS17_dict, 'erba_medica_II_taglio': ERBAMEDICA2_dict, 'erba_prato_stabile': ERBAPRASTA_dict, 'fieno_loietto': FIENOLOIETTO_dict, 'fieno_medica_I_taglio': FIEALIMENTOD1_dict, 'fieno_medica_II_taglio': FIEALIMENTOD2_dict, 'fieno_prato_stabile_I_taglio': FIEPRASTA1TA_dict, 'fieno_prato_stabile_II_taglio': FIEPRASTA2TA_dict, 'fieno_silos_medica': FIENOSILOMED_dict, 'insilato_loietto': INSILOIETTO_dict, 'insilato_mais': INSILOMAIS_dict, 'paglia_frumento': PAGLIA_dict, 'pastone_mais_granella': PASTOMAISGRA_dict, 'pastone_mais_integrale': PASTOMAISINT_dict, 'avena': AVENA_dict, 'frumento_tenero': FRUTENERO_dict, 'mais_granella': MAISGRA_dict, 'orzo': ORZO_dict, 'sorgo': SORGO_dict, 'triticale': TRITICALE_dict, 'arachide_farina_estrazione': ARACHIDEFE_dict, 'colza_farina_estrazione': COLZAFE_dict, 'cotone_farina_estrazione': COTONEFE_dict, 'girasole_farina_estrazione_24x100': GIRASOLEFE24_dict, 'girasole_farina_estrazione_34x100': GIRASOLEFE34_dict, 'lino_farina_estrazione': LINOFE_dict, 'soia_farina_estrazione_45x100': SOIAFE45_dict, 'soia_farina_estrazione_50x100': SOIAFE50_dict, 'bietola_polpe_secche': BIEPOLSECCHE_dict, 'bietola_polpe_surpressate': BIEPOLSURPRE_dict, 'carruba_polpa_denocciolata': CARRUPOLDENO_dict, 'cotone_semi': COTONESEMI_dict, 'crusca_frumento_duro': CRUSCAFRUDURO_dict, 'crusca_frumento_tenero': CRUFRUTENERO_dict, 'cruschello_frumento_duro': CRUSCHELLOFRUDU_dict, 'cruschello_frumento_tenero': CRUSCHELLOFRUTE_dict, 'frumento_duro_farinaccio': FRUDUFARINACCIO_dict, 'frumento_tenero_farinaccio': FRUTENEFARINACCIO_dict, 'frumento_tritello': FRUMENTOTRI_dict, 'mais_glutine': MAISGLUTINE_dict, 'mais_residui_distilleria': MAISDISTILLERS_dict, 'mais_semola_glutinata': MAISSEMOGLU_dict, 'orzo_radichette_malto': ORZORADIMALTO_dict, 'orzo_trebbie_birra': ORZOTREBBIEBI_dict, 'riso_farinaccio': RISOFARINACCIO_dict, 'soia_buccette': SOIABUCCETTE_dict, 'favino': FAVINO_dict, 'lupino': LUPINO_dict, 'pisello': PISELLO_dict, 'soia_integrale': SOIAINTEGRALE_dict, 'agrumi_pastazzo_secco': AGRUMIPASTAZZO_dict, 'birra_lievito': BIRRALIEVITO_dict, 'calcio_saponi': CALCIOSAPONI_dict, 'cocco_pannello': COCCOPANNELLO_dict, 'frumento_tenero_germe': FRUTEGERME_dict, 'latte_magro_polvere': LATTEMAPOL_dict, 'latte_siero': LATTESIERO_dict, 'manioca': MANIOCA_dict, 'melasso_barbabietola': MELASSOBARBA_dict, 'melasso_canna': MELASSOCANNA_dict, 'patate_essiccate': PATATEESSI_dict, 'proteina_patata': PROTEINAPATA_dict, 'riso_gemma': RISOGEMMA_dict, 'riso_grana_verde': RISOGRANAVER_dict, 'riso_pula_commerciale': RISOPULACOMM_dict, 'riso_pula_vergine': RISOPULAVERG_dict, 'riso_rottura': RISOROTT_dict}



ALIMENTO = askstring('Entry', 'scegli un alimento')
print(ALIMENTO)

print(alimenti['%s' % ALIMENTO])

